// Generated by `pnpm openapi:contracts`. Do not edit directly.

import type { ZodOpenApiOperationObject } from 'zod-openapi';
import { defineOperation } from '@/openapi/operation';

const operation1 = defineOperation({
  method: 'get',
  path: '/api/2fa/status',
  audience: 'public',
  auth: 'bearer',
  operation: {
    operationId: 'get2faStatus',
    summary: 'Get 2fa status',
    tags: ['Two-factor authentication'],
    responses: {
      '200': {
        description: 'The operation completed successfully.',
        content: {
          'application/json': {
            schema: {
              anyOf: [
                {
                  type: 'object',
                  properties: {
                    isEnabled: {
                      type: 'boolean',
                    },
                    isRequired: {
                      type: 'boolean',
                    },
                    requiredReason: {
                      type: 'null',
                    },
                    isConfigured: {
                      type: 'boolean',
                    },
                    globalRequired: {
                      type: 'boolean',
                    },
                  },
                  required: [
                    'isEnabled',
                    'isRequired',
                    'requiredReason',
                    'isConfigured',
                    'globalRequired',
                  ],
                },
                {
                  type: 'object',
                  properties: {
                    isEnabled: {
                      type: 'boolean',
                    },
                    isRequired: {
                      type: 'boolean',
                    },
                    requiredReason: {
                      type: 'string',
                    },
                    isConfigured: {
                      type: 'boolean',
                    },
                    globalRequired: {
                      type: 'boolean',
                    },
                  },
                  required: [
                    'isEnabled',
                    'isRequired',
                    'requiredReason',
                    'isConfigured',
                    'globalRequired',
                  ],
                },
              ],
            },
          },
        },
      },
      '401': {
        description: 'Unauthorized.',
        content: {
          'application/json': {
            example: {
              error: {
                message: 'Unauthorized.',
                code: 'unauthorized',
                status: 401,
              },
            },
            schema: {
              $ref: '#/components/schemas/ApiError',
            },
          },
        },
      },
    },
  } as ZodOpenApiOperationObject,
});

export const operations = [operation1] as const;
