// Generated by `pnpm openapi:contracts`. Do not edit directly.

import type { ZodOpenApiOperationObject } from 'zod-openapi';
import { defineOperation } from '@/openapi/operation';

const operation1 = defineOperation({
  method: 'get',
  path: '/api/websites/{websiteId}/sessions/{sessionId}/activity',
  audience: 'public',
  auth: 'bearer-or-share',
  operation: {
    operationId: 'getWebsiteSessionActivity',
    summary: 'Get websites website id sessions session id activity',
    description:
      'Returns activity for the specified session and sessions linked by visitor identity, using the requested date range and optional distinct ID.',
    tags: ['Websites'],
    parameters: [
      {
        name: 'websiteId',
        in: 'path',
        required: true,
        schema: {
          type: 'string',
        },
        description: 'ID of the website.',
      },
      {
        name: 'sessionId',
        in: 'path',
        required: true,
        schema: {
          type: 'string',
        },
        description: 'ID of the visitor session.',
      },
      {
        name: 'startAt',
        in: 'query',
        required: false,
        schema: {
          type: 'integer',
        },
        description: 'Start of the date range as a Unix timestamp in milliseconds.',
      },
      {
        name: 'endAt',
        in: 'query',
        required: false,
        schema: {
          type: 'integer',
        },
        description: 'End of the date range as a Unix timestamp in milliseconds.',
      },
      {
        name: 'distinctId',
        in: 'query',
        required: false,
        schema: {
          type: 'string',
        },
        description: 'Custom identifier assigned to the visitor.',
      },
      {
        name: 'period',
        in: 'query',
        required: false,
        schema: {
          type: 'string',
          enum: [
            'today',
            '24h',
            '7d',
            '30d',
            '0day',
            '24hour',
            '0week',
            '7day',
            '0month',
            '30day',
            '90day',
            '0year',
            '6month',
            '12month',
          ],
        },
        description:
          'Relative date range, for example 7d or 30day, used instead of an explicit startAt/endAt range.',
      },
    ],
    responses: {
      '200': {
        description: 'The operation completed successfully.',
        content: {
          'application/json': {
            schema: {
              type: 'array',
              items: {
                type: 'object',
                properties: {
                  createdAt: {
                    anyOf: [
                      {
                        type: 'string',
                      },
                      {
                        type: 'string',
                        format: 'date-time',
                      },
                    ],
                    description: 'Date and time the record was created.',
                  },
                  urlPath: {
                    type: 'string',
                    description: 'Path portion of the page URL.',
                  },
                  urlQuery: {
                    type: 'string',
                    description: 'Query string portion of the page URL.',
                  },
                  referrerDomain: {
                    type: 'string',
                    description: 'Domain of the referring page.',
                  },
                  eventId: {
                    type: 'string',
                    description: 'ID of the event.',
                  },
                  eventType: {
                    type: 'number',
                    description: 'Event type: 1 for a pageview or 2 for a custom event.',
                  },
                  eventName: {
                    type: 'string',
                    description: 'Name of the custom event.',
                  },
                  visitId: {
                    type: 'string',
                    description: 'ID of the visit.',
                  },
                  hostname: {
                    type: 'string',
                    description: 'Hostname on which the activity occurred.',
                  },
                  hasData: {
                    type: 'boolean',
                  },
                },
                required: [
                  'createdAt',
                  'urlPath',
                  'urlQuery',
                  'referrerDomain',
                  'eventId',
                  'eventType',
                  'eventName',
                  'visitId',
                  'hostname',
                  'hasData',
                ],
              },
            },
          },
        },
      },
      '400': {
        description: 'Bad request.',
        content: {
          'application/json': {
            example: {
              error: {
                message: 'Bad request.',
                code: 'bad-request',
                status: 400,
              },
            },
            schema: {
              $ref: '#/components/schemas/ApiError',
            },
          },
        },
      },
      '401': {
        description: 'Unauthorized.',
        content: {
          'application/json': {
            example: {
              error: {
                message: 'Unauthorized.',
                code: 'unauthorized',
                status: 401,
              },
            },
            schema: {
              $ref: '#/components/schemas/ApiError',
            },
          },
        },
      },
    },
  } as ZodOpenApiOperationObject,
});

export const operations = [operation1] as const;
