// Generated by `pnpm openapi:contracts`. Do not edit directly.

import type { ZodOpenApiOperationObject } from 'zod-openapi';
import { defineOperation } from '@/openapi/operation';

const operation1 = defineOperation({
  method: 'get',
  path: '/api/websites/{websiteId}/sessions/{sessionId}/activity',
  audience: 'public',
  auth: 'bearer-or-share',
  operation: {
    operationId: 'getWebsiteSessionActivity',
    summary: 'Get websites website id sessions session id activity',
    tags: ['Websites'],
    'x-umami-oauth-scope': 'analytics:read',
    parameters: [
      {
        name: 'websiteId',
        in: 'path',
        required: true,
        schema: {
          type: 'string',
        },
      },
      {
        name: 'sessionId',
        in: 'path',
        required: true,
        schema: {
          type: 'string',
        },
      },
      {
        name: 'startAt',
        in: 'query',
        required: true,
        schema: {
          type: 'integer',
        },
      },
      {
        name: 'endAt',
        in: 'query',
        required: true,
        schema: {
          type: 'integer',
        },
      },
      {
        name: 'distinctId',
        in: 'query',
        required: false,
        schema: {
          type: 'string',
        },
      },
    ],
    responses: {
      '200': {
        description: 'The operation completed successfully.',
        content: {
          'application/json': {
            schema: {
              type: 'array',
              items: {
                type: 'object',
                properties: {
                  createdAt: {
                    anyOf: [
                      {
                        type: 'string',
                      },
                      {
                        type: 'string',
                        format: 'date-time',
                      },
                    ],
                  },
                  urlPath: {
                    type: 'string',
                  },
                  urlQuery: {
                    type: 'string',
                  },
                  referrerDomain: {
                    type: 'string',
                  },
                  eventId: {
                    type: 'string',
                  },
                  eventType: {
                    type: 'number',
                  },
                  eventName: {
                    type: 'string',
                  },
                  visitId: {
                    type: 'string',
                  },
                  hostname: {
                    type: 'string',
                  },
                  hasData: {
                    type: 'boolean',
                  },
                },
                required: [
                  'createdAt',
                  'urlPath',
                  'urlQuery',
                  'referrerDomain',
                  'eventId',
                  'eventType',
                  'eventName',
                  'visitId',
                  'hostname',
                  'hasData',
                ],
              },
            },
          },
        },
      },
      '400': {
        description: 'Bad request.',
        content: {
          'application/json': {
            example: {
              error: {
                message: 'Bad request.',
                code: 'bad-request',
                status: 400,
              },
            },
            schema: {
              $ref: '#/components/schemas/ApiError',
            },
          },
        },
      },
      '401': {
        description: 'Unauthorized.',
        content: {
          'application/json': {
            example: {
              error: {
                message: 'Unauthorized.',
                code: 'unauthorized',
                status: 401,
              },
            },
            schema: {
              $ref: '#/components/schemas/ApiError',
            },
          },
        },
      },
    },
  } as ZodOpenApiOperationObject,
});

export const operations = [operation1] as const;
