// Generated by `pnpm openapi:contracts`. Do not edit directly.

import type { ZodOpenApiOperationObject } from 'zod-openapi';
import { defineOperation } from '@/openapi/operation';

const operation1 = defineOperation({
  method: 'get',
  path: '/api/websites/{websiteId}/session-data/numeric-series',
  audience: 'public',
  auth: 'bearer-or-share',
  operation: {
    operationId: 'getWebsitesWebsiteIdSessionDataNumericSeries',
    summary: 'Get websites website id session data numeric series',
    description:
      'Get websites website id session data numeric series. The request and response models are derived from the validated route contract.',
    tags: ['Websites'],
    parameters: [
      {
        name: 'websiteId',
        in: 'path',
        required: true,
        schema: {
          type: 'string',
        },
      },
      {
        name: 'startAt',
        in: 'query',
        required: true,
        schema: {
          type: 'integer',
        },
      },
      {
        name: 'endAt',
        in: 'query',
        required: true,
        schema: {
          type: 'integer',
        },
      },
      {
        name: 'propertyName',
        in: 'query',
        required: true,
        schema: {
          type: 'string',
        },
      },
      {
        name: 'metric',
        in: 'query',
        required: false,
        schema: {
          type: 'string',
          enum: ['sum', 'avg', 'count'],
        },
      },
      {
        name: 'timezone',
        in: 'query',
        required: false,
        schema: {
          type: 'string',
        },
      },
      {
        name: 'unit',
        in: 'query',
        required: false,
        schema: {
          type: 'string',
        },
      },
      {
        name: 'path',
        in: 'query',
        required: false,
        schema: {
          type: 'string',
        },
      },
      {
        name: 'referrer',
        in: 'query',
        required: false,
        schema: {
          type: 'string',
        },
      },
      {
        name: 'title',
        in: 'query',
        required: false,
        schema: {
          type: 'string',
        },
      },
      {
        name: 'query',
        in: 'query',
        required: false,
        schema: {
          type: 'string',
        },
      },
      {
        name: 'os',
        in: 'query',
        required: false,
        schema: {
          type: 'string',
        },
      },
      {
        name: 'browser',
        in: 'query',
        required: false,
        schema: {
          type: 'string',
        },
      },
      {
        name: 'device',
        in: 'query',
        required: false,
        schema: {
          type: 'string',
        },
      },
      {
        name: 'country',
        in: 'query',
        required: false,
        schema: {
          type: 'string',
        },
      },
      {
        name: 'region',
        in: 'query',
        required: false,
        schema: {
          type: 'string',
        },
      },
      {
        name: 'city',
        in: 'query',
        required: false,
        schema: {
          type: 'string',
        },
      },
      {
        name: 'tag',
        in: 'query',
        required: false,
        schema: {
          type: 'string',
        },
      },
      {
        name: 'hostname',
        in: 'query',
        required: false,
        schema: {
          type: 'string',
        },
      },
      {
        name: 'distinctId',
        in: 'query',
        required: false,
        schema: {
          type: 'string',
        },
      },
      {
        name: 'language',
        in: 'query',
        required: false,
        schema: {
          type: 'string',
        },
      },
      {
        name: 'event',
        in: 'query',
        required: false,
        schema: {
          type: 'string',
        },
      },
      {
        name: 'utmSource',
        in: 'query',
        required: false,
        schema: {
          type: 'string',
        },
      },
      {
        name: 'utmMedium',
        in: 'query',
        required: false,
        schema: {
          type: 'string',
        },
      },
      {
        name: 'utmCampaign',
        in: 'query',
        required: false,
        schema: {
          type: 'string',
        },
      },
      {
        name: 'utmContent',
        in: 'query',
        required: false,
        schema: {
          type: 'string',
        },
      },
      {
        name: 'utmTerm',
        in: 'query',
        required: false,
        schema: {
          type: 'string',
        },
      },
      {
        name: 'excludeBounce',
        in: 'query',
        required: false,
        schema: {
          type: 'string',
        },
      },
      {
        name: 'segment',
        in: 'query',
        required: false,
        schema: {
          type: 'string',
          format: 'uuid',
        },
      },
      {
        name: 'cohort',
        in: 'query',
        required: false,
        schema: {
          type: 'string',
          format: 'uuid',
        },
      },
      {
        name: 'eventType',
        in: 'query',
        required: false,
        schema: {
          type: 'integer',
          minimum: 1,
        },
      },
      {
        name: 'match',
        in: 'query',
        required: false,
        schema: {
          type: 'string',
          enum: ['all', 'any'],
        },
      },
    ],
    responses: {
      '200': {
        description: 'The operation completed successfully.',
        content: {
          'application/json': {
            schema: {
              type: 'array',
              items: {
                type: 'object',
                properties: {
                  t: {
                    type: 'string',
                  },
                  y: {
                    type: 'number',
                  },
                },
                required: ['t', 'y'],
              },
            },
          },
        },
      },
      '400': {
        description: 'Bad request.',
        content: {
          'application/json': {
            example: {
              error: {
                message: 'Bad request.',
                code: 'bad-request',
                status: 400,
              },
            },
            schema: {
              $ref: '#/components/schemas/ApiError',
            },
          },
        },
      },
      '401': {
        description: 'Unauthorized.',
        content: {
          'application/json': {
            example: {
              error: {
                message: 'Unauthorized.',
                code: 'unauthorized',
                status: 401,
              },
            },
            schema: {
              $ref: '#/components/schemas/ApiError',
            },
          },
        },
      },
    },
  } as ZodOpenApiOperationObject,
});

export const operations = [operation1] as const;
