// Generated by `pnpm openapi:contracts`. Do not edit directly.

import type { ZodOpenApiOperationObject } from 'zod-openapi';
import { defineOperation } from '@/openapi/operation';

const operation1 = defineOperation({
  method: 'post',
  path: '/api/reports/heatmap',
  audience: 'public',
  auth: 'bearer-or-share',
  operation: {
    operationId: 'postReportsHeatmap',
    summary: 'Create or update reports heatmap',
    description:
      'Create or update reports heatmap. The request and response models are derived from the validated route contract.',
    tags: ['Reports'],
    requestBody: {
      required: true,
      content: {
        'application/json': {
          schema: {
            type: 'object',
            properties: {
              websiteId: {
                type: 'string',
                format: 'uuid',
              },
              filters: {
                type: 'object',
                additionalProperties: true,
              },
              type: {
                type: 'string',
              },
              parameters: {
                type: 'object',
                additionalProperties: true,
              },
            },
            required: ['websiteId', 'filters', 'type', 'parameters'],
          },
        },
      },
    },
    responses: {
      '200': {
        description: 'The operation completed successfully.',
        content: {
          'application/json': {
            schema: {
              type: 'object',
              properties: {
                mode: {
                  anyOf: [
                    {
                      const: 'click',
                    },
                    {
                      const: 'scroll',
                    },
                  ],
                },
                pages: {
                  type: 'array',
                  items: {
                    type: 'object',
                    properties: {
                      urlPath: {
                        type: 'string',
                      },
                      count: {
                        type: 'number',
                      },
                      sessions: {
                        type: 'number',
                      },
                    },
                    required: ['urlPath', 'count', 'sessions'],
                  },
                },
                points: {
                  type: 'array',
                  items: {
                    type: 'object',
                    properties: {
                      x: {
                        type: 'number',
                      },
                      y: {
                        type: 'number',
                      },
                      pageX: {
                        type: 'number',
                      },
                      pageY: {
                        type: 'number',
                      },
                      pageW: {
                        type: 'number',
                      },
                      pageH: {
                        type: 'number',
                      },
                      viewportW: {
                        type: 'number',
                      },
                      viewportH: {
                        type: 'number',
                      },
                      count: {
                        type: 'number',
                      },
                    },
                    required: [
                      'x',
                      'y',
                      'pageX',
                      'pageY',
                      'pageW',
                      'pageH',
                      'viewportW',
                      'viewportH',
                      'count',
                    ],
                  },
                },
                snapshot: {
                  type: 'object',
                  properties: {
                    kind: {
                      const: 'iframe',
                    },
                    id: {
                      type: 'string',
                    },
                    url: {
                      type: 'string',
                    },
                    pageW: {
                      type: 'number',
                    },
                    pageH: {
                      type: 'number',
                    },
                    viewportW: {
                      type: 'number',
                    },
                    viewportH: {
                      type: 'number',
                    },
                  },
                  required: ['kind', 'id', 'url', 'pageW', 'pageH', 'viewportW', 'viewportH'],
                },
                scroll: {
                  type: 'object',
                  properties: {
                    buckets: {
                      type: 'array',
                      items: {
                        type: 'object',
                        properties: {
                          depth: {
                            type: 'number',
                          },
                          sessions: {
                            type: 'number',
                          },
                          pageW: {
                            type: 'number',
                          },
                          pageH: {
                            type: 'number',
                          },
                          viewportW: {
                            type: 'number',
                          },
                          viewportH: {
                            type: 'number',
                          },
                        },
                        required: ['depth', 'sessions', 'pageW', 'pageH', 'viewportW', 'viewportH'],
                      },
                    },
                    totalSessions: {
                      type: 'number',
                    },
                    pageW: {
                      type: 'number',
                    },
                    pageH: {
                      type: 'number',
                    },
                    viewportW: {
                      type: 'number',
                    },
                    viewportH: {
                      type: 'number',
                    },
                  },
                  required: [
                    'buckets',
                    'totalSessions',
                    'pageW',
                    'pageH',
                    'viewportW',
                    'viewportH',
                  ],
                },
              },
              required: ['mode', 'pages', 'points', 'snapshot', 'scroll'],
            },
          },
        },
      },
      '400': {
        description: 'Bad request.',
        content: {
          'application/json': {
            example: {
              error: {
                message: 'Bad request.',
                code: 'bad-request',
                status: 400,
              },
            },
            schema: {
              $ref: '#/components/schemas/ApiError',
            },
          },
        },
      },
      '401': {
        description: 'Unauthorized.',
        content: {
          'application/json': {
            example: {
              error: {
                message: 'Unauthorized.',
                code: 'unauthorized',
                status: 401,
              },
            },
            schema: {
              $ref: '#/components/schemas/ApiError',
            },
          },
        },
      },
    },
  } as ZodOpenApiOperationObject,
});

export const operations = [operation1] as const;
