// Generated by `pnpm openapi:contracts`. Do not edit directly.

import type { ZodOpenApiOperationObject } from 'zod-openapi';
import { defineOperation } from '@/openapi/operation';

const operation1 = defineOperation({
  method: 'get',
  path: '/api/links/charts',
  audience: 'public',
  auth: 'bearer-or-share',
  operation: {
    operationId: 'getLinksCharts',
    summary: 'Get links charts',
    description:
      'Get links charts. The request and response models are derived from the validated route contract.',
    tags: ['Links'],
    parameters: [
      {
        name: 'ids',
        in: 'query',
        required: true,
        schema: {
          type: 'string',
        },
      },
      {
        name: 'startAt',
        in: 'query',
        required: false,
        schema: {
          type: 'integer',
        },
      },
      {
        name: 'endAt',
        in: 'query',
        required: false,
        schema: {
          type: 'integer',
        },
      },
      {
        name: 'timezone',
        in: 'query',
        required: false,
        schema: {
          type: 'string',
        },
      },
    ],
    responses: {
      '200': {
        description: 'The operation completed successfully.',
        content: {
          'application/json': {
            schema: {
              type: 'object',
              properties: {
                data: {
                  type: 'object',
                  properties: {},
                  additionalProperties: {
                    type: 'object',
                    properties: {
                      values: {
                        type: 'array',
                        items: {
                          type: 'number',
                        },
                      },
                      total: {
                        type: 'number',
                      },
                    },
                    required: ['values', 'total'],
                  },
                },
              },
              required: ['data'],
            },
          },
        },
      },
      '400': {
        description: 'Bad request.',
        content: {
          'application/json': {
            example: {
              error: {
                message: 'Bad request.',
                code: 'bad-request',
                status: 400,
              },
            },
            schema: {
              $ref: '#/components/schemas/ApiError',
            },
          },
        },
      },
      '401': {
        description: 'Unauthorized.',
        content: {
          'application/json': {
            example: {
              error: {
                message: 'Unauthorized.',
                code: 'unauthorized',
                status: 401,
              },
            },
            schema: {
              $ref: '#/components/schemas/ApiError',
            },
          },
        },
      },
    },
  } as ZodOpenApiOperationObject,
});

export const operations = [operation1] as const;
