# To deploy on Cloudflare Workers, please follow these two steps
# 
# 1. Build the Application: pnpm run cloudflare:build
# 2. Deploy the Application: pnpm run cloudflare:deploy
#
# You need add `DATABASE_URL` variable in build environment and runtime environment.
#
# When use Hyperdrive, you don't need to add the `DATABASE_URL` variable in the runtime environment.
main = ".open-next/worker.js"
name = "umami"
compatibility_date = "2025-09-15"
compatibility_flags = ["nodejs_compat", "global_fetch_strictly_public"]
workers_dev = false

[observability]
enabled = true

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[[services]]
binding = "WORKER_SELF_REFERENCE"
service = "umami"

# Advanced users can enable hyperdrive to optimize database connection latency. 
# For usage, please refer to https://developers.cloudflare.com/hyperdrive/get-started/.
# [[hyperdrive]]
# binding = "HYPERDRIVE"
# id = ""
