import { useMemo } from 'react';
import { useNavigation } from './useNavigation';

export function useFilterParameters() {
  const {
    query: {
      path,
      referrer,
      title,
      query,
      host,
      os,
      browser,
      device,
      country,
      region,
      city,
      event,
      tag,
      hostname,
      distinctId,
      utmSource,
      utmMedium,
      utmCampaign,
      utmContent,
      utmTerm,
      page,
      pageSize,
      search,
      segment,
      cohort,
      excludeBounce,
    },
  } = useNavigation();

  return useMemo(() => {
    return {
      path,
      referrer,
      title,
      query,
      host,
      os,
      browser,
      device,
      country,
      region,
      city,
      event,
      tag,
      hostname,
      distinctId,
      utmSource,
      utmMedium,
      utmCampaign,
      utmContent,
      utmTerm,
      search,
      segment,
      cohort,
      excludeBounce,
    };
  }, [
    path,
    referrer,
    title,
    query,
    host,
    os,
    browser,
    device,
    country,
    region,
    city,
    event,
    tag,
    hostname,
    distinctId,
    utmSource,
    utmMedium,
    utmCampaign,
    utmContent,
    utmTerm,
    page,
    pageSize,
    search,
    segment,
    cohort,
    excludeBounce,
  ]);
}
