// Generated by `pnpm openapi:contracts`. Do not edit directly.

import type { ZodOpenApiOperationObject } from 'zod-openapi';
import { defineOperation } from '@/openapi/operation';

const operation1 = defineOperation({
  method: 'get',
  path: '/api/config',
  audience: 'internal',
  auth: 'none',
  operation: {
    operationId: 'getConfig',
    summary: 'Get config',
    tags: ['Configuration'],
    responses: {
      '200': {
        description: 'The operation completed successfully.',
        content: {
          'application/json': {
            schema: {
              type: 'object',
              properties: {
                cloudMode: {
                  type: 'boolean',
                },
                faviconUrl: {
                  type: 'string',
                },
                linksUrl: {
                  type: 'string',
                },
                pixelsUrl: {
                  type: 'string',
                },
                privateMode: {
                  type: 'boolean',
                },
                sessionDeletionEnabled: {
                  type: 'boolean',
                },
                telemetryDisabled: {
                  type: 'boolean',
                },
                trackerScriptName: {
                  type: 'string',
                },
                updatesDisabled: {
                  type: 'boolean',
                },
              },
              required: [
                'cloudMode',
                'faviconUrl',
                'linksUrl',
                'pixelsUrl',
                'privateMode',
                'sessionDeletionEnabled',
                'telemetryDisabled',
                'trackerScriptName',
                'updatesDisabled',
              ],
            },
          },
        },
      },
    },
  } as ZodOpenApiOperationObject,
});

export const operations = [operation1] as const;
