// Generated by `pnpm openapi:contracts`. Do not edit directly.

import type { ZodOpenApiOperationObject } from 'zod-openapi';
import { defineOperation } from '@/openapi/operation';

const operation1 = defineOperation({
  method: 'get',
  path: '/api/websites/{websiteId}/reports',
  audience: 'public',
  auth: 'bearer-or-share',
  operation: {
    operationId: 'getWebsitesWebsiteIdReports',
    summary: 'Get websites website id reports',
    tags: ['Websites'],
    parameters: [
      {
        name: 'websiteId',
        in: 'path',
        required: true,
        schema: {
          type: 'string',
        },
      },
      {
        name: 'type',
        in: 'query',
        required: false,
        schema: {
          type: 'string',
        },
      },
      {
        name: 'page',
        in: 'query',
        required: false,
        schema: {
          type: 'integer',
          minimum: 1,
        },
      },
      {
        name: 'pageSize',
        in: 'query',
        required: false,
        schema: {
          type: 'integer',
          minimum: 1,
        },
      },
      {
        name: 'maxResults',
        in: 'query',
        required: false,
        schema: {
          type: 'integer',
          minimum: 1,
        },
      },
    ],
    responses: {
      '200': {
        description: 'The operation completed successfully.',
        content: {
          'application/json': {
            schema: {
              type: 'object',
              properties: {
                data: {
                  type: 'array',
                  items: {
                    allOf: [
                      {
                        type: 'object',
                        properties: {
                          id: {
                            type: 'string',
                          },
                          userId: {
                            type: 'string',
                          },
                          createdAt: {
                            type: 'string',
                            format: 'date-time',
                          },
                          updatedAt: {
                            type: 'string',
                            format: 'date-time',
                          },
                          name: {
                            type: 'string',
                          },
                          type: {
                            type: 'string',
                          },
                          description: {
                            type: 'string',
                          },
                          parameters: {
                            anyOf: [
                              {
                                type: 'string',
                              },
                              {
                                type: 'number',
                              },
                              {
                                const: false,
                              },
                              {
                                const: true,
                              },
                              {
                                type: 'object',
                                properties: {},
                                additionalProperties: {
                                  anyOf: [
                                    {
                                      type: 'string',
                                    },
                                    {
                                      type: 'number',
                                    },
                                    {
                                      const: false,
                                    },
                                    {
                                      const: true,
                                    },
                                    {},
                                    {
                                      type: 'object',
                                      properties: {
                                        length: {
                                          type: 'number',
                                        },
                                      },
                                      required: ['length'],
                                    },
                                  ],
                                },
                              },
                              {
                                type: 'object',
                                properties: {
                                  length: {
                                    type: 'number',
                                  },
                                },
                                required: ['length'],
                              },
                            ],
                          },
                          websiteId: {
                            type: 'string',
                          },
                        },
                        required: [
                          'id',
                          'userId',
                          'createdAt',
                          'updatedAt',
                          'name',
                          'type',
                          'description',
                          'parameters',
                          'websiteId',
                        ],
                      },
                      {
                        type: 'object',
                        properties: {
                          website: {
                            type: 'object',
                            properties: {
                              domain: {
                                type: 'string',
                              },
                              userId: {
                                type: 'string',
                              },
                            },
                            required: ['domain', 'userId'],
                          },
                        },
                      },
                    ],
                  },
                },
                count: {
                  type: 'number',
                },
                page: {
                  type: 'number',
                },
                pageSize: {
                  type: 'number',
                },
                orderBy: {
                  type: 'string',
                },
                sortDescending: {
                  type: 'boolean',
                },
                search: {
                  type: 'string',
                },
                isCapped: {
                  type: 'boolean',
                },
              },
              required: ['data', 'count', 'page', 'pageSize'],
            },
          },
        },
      },
      '400': {
        description: 'Bad request.',
        content: {
          'application/json': {
            example: {
              error: {
                message: 'Bad request.',
                code: 'bad-request',
                status: 400,
              },
            },
            schema: {
              $ref: '#/components/schemas/ApiError',
            },
          },
        },
      },
      '401': {
        description: 'Unauthorized.',
        content: {
          'application/json': {
            example: {
              error: {
                message: 'Unauthorized.',
                code: 'unauthorized',
                status: 401,
              },
            },
            schema: {
              $ref: '#/components/schemas/ApiError',
            },
          },
        },
      },
    },
  } as ZodOpenApiOperationObject,
});

export const operations = [operation1] as const;
