// Generated by `pnpm openapi:contracts`. Do not edit directly.

import type { ZodOpenApiOperationObject } from 'zod-openapi';
import { defineOperation } from '@/openapi/operation';

const operation1 = defineOperation({
  method: 'get',
  path: '/api/pixels',
  audience: 'public',
  auth: 'bearer',
  operation: {
    operationId: 'getPixels',
    summary: 'Get pixels',
    tags: ['Pixels'],
    parameters: [
      {
        name: 'page',
        in: 'query',
        required: false,
        schema: {
          type: 'integer',
          minimum: 1,
        },
      },
      {
        name: 'pageSize',
        in: 'query',
        required: false,
        schema: {
          type: 'integer',
          minimum: 1,
        },
      },
      {
        name: 'maxResults',
        in: 'query',
        required: false,
        schema: {
          type: 'integer',
          minimum: 1,
        },
      },
      {
        name: 'search',
        in: 'query',
        required: false,
        schema: {
          type: 'string',
        },
      },
      {
        name: 'orderBy',
        in: 'query',
        required: false,
        schema: {
          type: 'string',
        },
      },
      {
        name: 'sortDescending',
        in: 'query',
        required: false,
        schema: {
          type: 'string',
          enum: ['true', 'false'],
        },
      },
    ],
    responses: {
      '200': {
        description: 'The operation completed successfully.',
        content: {
          'application/json': {
            schema: {
              type: 'object',
              properties: {
                data: {
                  type: 'array',
                  items: {
                    type: 'object',
                    properties: {
                      id: {
                        type: 'string',
                      },
                      userId: {
                        type: 'string',
                      },
                      createdAt: {
                        type: 'string',
                        format: 'date-time',
                      },
                      updatedAt: {
                        type: 'string',
                        format: 'date-time',
                      },
                      deletedAt: {
                        type: 'string',
                        format: 'date-time',
                      },
                      name: {
                        type: 'string',
                      },
                      teamId: {
                        type: 'string',
                      },
                      slug: {
                        type: 'string',
                      },
                    },
                    required: [
                      'id',
                      'userId',
                      'createdAt',
                      'updatedAt',
                      'deletedAt',
                      'name',
                      'teamId',
                      'slug',
                    ],
                  },
                },
                count: {
                  type: 'number',
                },
                page: {
                  type: 'number',
                },
                pageSize: {
                  type: 'number',
                },
                orderBy: {
                  type: 'string',
                },
                sortDescending: {
                  type: 'boolean',
                },
                search: {
                  type: 'string',
                },
                isCapped: {
                  type: 'boolean',
                },
              },
              required: ['data', 'count', 'page', 'pageSize'],
            },
          },
        },
      },
      '400': {
        description: 'Bad request.',
        content: {
          'application/json': {
            example: {
              error: {
                message: 'Bad request.',
                code: 'bad-request',
                status: 400,
              },
            },
            schema: {
              $ref: '#/components/schemas/ApiError',
            },
          },
        },
      },
      '401': {
        description: 'Unauthorized.',
        content: {
          'application/json': {
            example: {
              error: {
                message: 'Unauthorized.',
                code: 'unauthorized',
                status: 401,
              },
            },
            schema: {
              $ref: '#/components/schemas/ApiError',
            },
          },
        },
      },
    },
  } as ZodOpenApiOperationObject,
});

const operation2 = defineOperation({
  method: 'post',
  path: '/api/pixels',
  audience: 'public',
  auth: 'bearer',
  operation: {
    operationId: 'createPixel',
    summary: 'Create or update pixels',
    tags: ['Pixels'],
    requestBody: {
      required: true,
      content: {
        'application/json': {
          schema: {
            type: 'object',
            properties: {
              name: {
                type: 'string',
                maxLength: 100,
              },
              slug: {
                type: 'string',
                minLength: 8,
                maxLength: 100,
              },
              teamId: {
                anyOf: [
                  {
                    type: 'string',
                  },
                  {
                    type: 'null',
                  },
                ],
              },
              id: {
                anyOf: [
                  {
                    type: 'string',
                    format: 'uuid',
                  },
                  {
                    type: 'null',
                  },
                ],
              },
            },
            required: ['name', 'slug'],
          },
        },
      },
    },
    responses: {
      '200': {
        description: 'The operation completed successfully.',
        content: {
          'application/json': {
            schema: {
              type: 'object',
              properties: {
                id: {
                  type: 'string',
                },
                userId: {
                  type: 'string',
                },
                createdAt: {
                  type: 'string',
                  format: 'date-time',
                },
                updatedAt: {
                  type: 'string',
                  format: 'date-time',
                },
                deletedAt: {
                  type: 'string',
                  format: 'date-time',
                },
                name: {
                  type: 'string',
                },
                teamId: {
                  type: 'string',
                },
                slug: {
                  type: 'string',
                },
              },
              required: [
                'id',
                'userId',
                'createdAt',
                'updatedAt',
                'deletedAt',
                'name',
                'teamId',
                'slug',
              ],
            },
          },
        },
      },
      '400': {
        description: 'Bad request.',
        content: {
          'application/json': {
            example: {
              error: {
                message: 'Bad request.',
                code: 'bad-request',
                status: 400,
              },
            },
            schema: {
              $ref: '#/components/schemas/ApiError',
            },
          },
        },
      },
      '401': {
        description: 'Unauthorized.',
        content: {
          'application/json': {
            example: {
              error: {
                message: 'Unauthorized.',
                code: 'unauthorized',
                status: 401,
              },
            },
            schema: {
              $ref: '#/components/schemas/ApiError',
            },
          },
        },
      },
    },
  } as ZodOpenApiOperationObject,
});

export const operations = [operation1, operation2] as const;
