// Generated by `pnpm openapi:contracts`. Do not edit directly.

import type { ZodOpenApiOperationObject } from 'zod-openapi';
import { defineOperation } from '@/openapi/operation';

const operation1 = defineOperation({
  method: 'get',
  path: '/api/auth/subscription',
  audience: 'public',
  auth: 'bearer-or-share',
  operation: {
    operationId: 'getAuthSubscription',
    summary: 'Get auth subscription',
    tags: ['Authentication'],
    parameters: [
      {
        name: 'teamId',
        in: 'query',
        required: false,
        schema: {
          type: 'string',
          format: 'uuid',
        },
      },
    ],
    responses: {
      '200': {
        description: 'The operation completed successfully.',
        content: {
          'application/json': {
            schema: {
              anyOf: [
                {
                  type: 'object',
                  properties: {
                    error: {
                      type: 'object',
                      properties: {
                        message: {
                          type: 'string',
                        },
                        code: {
                          type: 'string',
                        },
                        status: {
                          type: 'number',
                        },
                      },
                      required: ['message', 'code', 'status'],
                    },
                  },
                  required: ['error'],
                },
                {
                  type: 'object',
                  properties: {
                    isPro: {
                      type: 'boolean',
                    },
                    isBusiness: {
                      type: 'boolean',
                    },
                    isNoBilling: {
                      type: 'boolean',
                    },
                    hasSubscription: {
                      type: 'boolean',
                    },
                    unlimitedWebsites: {
                      type: 'boolean',
                    },
                  },
                  required: [
                    'isPro',
                    'isBusiness',
                    'isNoBilling',
                    'hasSubscription',
                    'unlimitedWebsites',
                  ],
                },
              ],
            },
          },
        },
      },
      '400': {
        description: 'Bad request.',
        content: {
          'application/json': {
            example: {
              error: {
                message: 'Bad request.',
                code: 'bad-request',
                status: 400,
              },
            },
            schema: {
              $ref: '#/components/schemas/ApiError',
            },
          },
        },
      },
      '401': {
        description: 'Unauthorized.',
        content: {
          'application/json': {
            example: {
              error: {
                message: 'Unauthorized.',
                code: 'unauthorized',
                status: 401,
              },
            },
            schema: {
              $ref: '#/components/schemas/ApiError',
            },
          },
        },
      },
    },
  } as ZodOpenApiOperationObject,
});

export const operations = [operation1] as const;
