// Generated by `pnpm openapi:contracts`. Do not edit directly.

import type { ZodOpenApiOperationObject } from 'zod-openapi';
import { defineOperation } from '@/openapi/operation';

const operation1 = defineOperation({
  method: 'get',
  path: '/api/websites/charts',
  audience: 'public',
  auth: 'bearer-or-share',
  operation: {
    operationId: 'getWebsitesCharts',
    summary: 'Get websites charts',
    description:
      'Returns visitor totals and chart data for the requested websites the caller can view, within the selected date range.',
    tags: ['Websites'],
    parameters: [
      {
        name: 'ids',
        in: 'query',
        required: true,
        schema: {
          type: 'string',
        },
        description: 'Comma-separated resource IDs. Provide between 1 and 20 IDs.',
      },
      {
        name: 'startAt',
        in: 'query',
        required: false,
        schema: {
          type: 'integer',
        },
        description: 'Start of the date range as a Unix timestamp in milliseconds.',
      },
      {
        name: 'endAt',
        in: 'query',
        required: false,
        schema: {
          type: 'integer',
        },
        description: 'End of the date range as a Unix timestamp in milliseconds.',
      },
      {
        name: 'timezone',
        in: 'query',
        required: false,
        schema: {
          type: 'string',
        },
        description:
          'IANA time zone used to interpret dates and group results, for example America/New_York.',
      },
      {
        name: 'period',
        in: 'query',
        required: false,
        schema: {
          type: 'string',
          enum: [
            'today',
            '24h',
            '7d',
            '30d',
            '0day',
            '24hour',
            '0week',
            '7day',
            '0month',
            '30day',
            '90day',
            '0year',
            '6month',
            '12month',
          ],
        },
        description:
          'Relative date range, for example 7d or 30day, used instead of an explicit startAt/endAt range.',
      },
    ],
    responses: {
      '200': {
        description: 'The operation completed successfully.',
        content: {
          'application/json': {
            schema: {
              type: 'object',
              properties: {
                data: {
                  type: 'object',
                  properties: {},
                  additionalProperties: {
                    type: 'object',
                    properties: {
                      values: {
                        type: 'array',
                        items: {
                          type: 'number',
                        },
                      },
                      total: {
                        type: 'number',
                      },
                    },
                    required: ['values', 'total'],
                  },
                  description: 'Data returned by the operation.',
                },
              },
              required: ['data'],
            },
          },
        },
      },
      '400': {
        description: 'Bad request.',
        content: {
          'application/json': {
            example: {
              error: {
                message: 'Bad request.',
                code: 'bad-request',
                status: 400,
              },
            },
            schema: {
              $ref: '#/components/schemas/ApiError',
            },
          },
        },
      },
      '401': {
        description: 'Unauthorized.',
        content: {
          'application/json': {
            example: {
              error: {
                message: 'Unauthorized.',
                code: 'unauthorized',
                status: 401,
              },
            },
            schema: {
              $ref: '#/components/schemas/ApiError',
            },
          },
        },
      },
    },
  } as ZodOpenApiOperationObject,
});

export const operations = [operation1] as const;
