// Generated by `pnpm openapi:contracts`. Do not edit directly.

import type { ZodOpenApiOperationObject } from 'zod-openapi';
import { defineOperation } from '@/openapi/operation';

const operation1 = defineOperation({
  method: 'get',
  path: '/api/teams/{teamId}/boards',
  audience: 'public',
  auth: 'bearer-or-share',
  operation: {
    operationId: 'getTeamsTeamIdBoards',
    summary: 'Get teams team id boards',
    description:
      'Get teams team id boards. The request and response models are derived from the validated route contract.',
    tags: ['Teams'],
    parameters: [
      {
        name: 'teamId',
        in: 'path',
        required: true,
        schema: {
          type: 'string',
        },
      },
      {
        name: 'page',
        in: 'query',
        required: false,
        schema: {
          type: 'integer',
          minimum: 1,
        },
      },
      {
        name: 'pageSize',
        in: 'query',
        required: false,
        schema: {
          type: 'integer',
          minimum: 1,
        },
      },
      {
        name: 'maxResults',
        in: 'query',
        required: false,
        schema: {
          type: 'integer',
          minimum: 1,
        },
      },
      {
        name: 'search',
        in: 'query',
        required: false,
        schema: {
          type: 'string',
        },
      },
      {
        name: 'orderBy',
        in: 'query',
        required: false,
        schema: {
          type: 'string',
        },
      },
      {
        name: 'sortDescending',
        in: 'query',
        required: false,
        schema: {
          type: 'string',
          enum: ['true', 'false'],
        },
      },
    ],
    responses: {
      '200': {
        description: 'The operation completed successfully.',
        content: {
          'application/json': {
            schema: {
              type: 'object',
              properties: {
                data: {
                  type: 'array',
                  items: {
                    type: 'object',
                    properties: {
                      id: {
                        type: 'string',
                      },
                      userId: {
                        type: 'string',
                      },
                      createdAt: {
                        type: 'string',
                        format: 'date-time',
                      },
                      updatedAt: {
                        type: 'string',
                        format: 'date-time',
                      },
                      name: {
                        type: 'string',
                      },
                      teamId: {
                        type: 'string',
                      },
                      type: {
                        type: 'string',
                      },
                      description: {
                        type: 'string',
                      },
                      parameters: {
                        anyOf: [
                          {
                            type: 'string',
                          },
                          {
                            type: 'number',
                          },
                          {
                            const: false,
                          },
                          {
                            const: true,
                          },
                          {
                            type: 'object',
                            properties: {},
                            additionalProperties: {
                              anyOf: [
                                {
                                  type: 'string',
                                },
                                {
                                  type: 'number',
                                },
                                {
                                  const: false,
                                },
                                {
                                  const: true,
                                },
                                {},
                                {
                                  type: 'object',
                                  properties: {
                                    length: {
                                      type: 'number',
                                    },
                                  },
                                  required: ['length'],
                                },
                              ],
                            },
                          },
                          {
                            type: 'object',
                            properties: {
                              length: {
                                type: 'number',
                              },
                            },
                            required: ['length'],
                          },
                        ],
                      },
                    },
                    required: [
                      'id',
                      'userId',
                      'createdAt',
                      'updatedAt',
                      'name',
                      'teamId',
                      'type',
                      'description',
                      'parameters',
                    ],
                  },
                },
                count: {
                  type: 'number',
                },
                page: {
                  type: 'number',
                },
                pageSize: {
                  type: 'number',
                },
                orderBy: {
                  type: 'string',
                },
                sortDescending: {
                  type: 'boolean',
                },
                search: {
                  type: 'string',
                },
                isCapped: {
                  type: 'boolean',
                },
              },
              required: ['data', 'count', 'page', 'pageSize'],
            },
          },
        },
      },
      '400': {
        description: 'Bad request.',
        content: {
          'application/json': {
            example: {
              error: {
                message: 'Bad request.',
                code: 'bad-request',
                status: 400,
              },
            },
            schema: {
              $ref: '#/components/schemas/ApiError',
            },
          },
        },
      },
      '401': {
        description: 'Unauthorized.',
        content: {
          'application/json': {
            example: {
              error: {
                message: 'Unauthorized.',
                code: 'unauthorized',
                status: 401,
              },
            },
            schema: {
              $ref: '#/components/schemas/ApiError',
            },
          },
        },
      },
    },
  } as ZodOpenApiOperationObject,
});

export const operations = [operation1] as const;
