-- AlterTable
ALTER TABLE `website_event` 
ADD COLUMN `fbclid` VARCHAR(255) NULL,
ADD COLUMN `gclid` VARCHAR(255) NULL,
ADD COLUMN `li_fat_id` VARCHAR(255) NULL,
ADD COLUMN `msclkid` VARCHAR(255) NULL,
ADD COLUMN `ttclid` VARCHAR(255) NULL,
ADD COLUMN `twclid` VARCHAR(255) NULL,
ADD COLUMN `utm_campaign` VARCHAR(255) NULL,
ADD COLUMN `utm_content` VARCHAR(255) NULL,
ADD COLUMN `utm_medium` VARCHAR(255) NULL,
ADD COLUMN `utm_source` VARCHAR(255) NULL,
ADD COLUMN `utm_term` VARCHAR(255) NULL;
