// Generated by `pnpm openapi:contracts`. Do not edit directly.

import type { ZodOpenApiOperationObject } from 'zod-openapi';
import { defineOperation } from '@/openapi/operation';

const operation1 = defineOperation({
  method: 'get',
  path: '/api/websites/{websiteId}/annotations',
  audience: 'public',
  auth: 'bearer-or-share',
  operation: {
    operationId: 'getWebsiteAnnotations',
    summary: 'Get websites website id annotations',
    tags: ['Websites'],
    parameters: [
      {
        name: 'websiteId',
        in: 'path',
        required: true,
        schema: {
          type: 'string',
        },
      },
      {
        name: 'startAt',
        in: 'query',
        required: false,
        schema: {
          type: 'number',
        },
      },
      {
        name: 'endAt',
        in: 'query',
        required: false,
        schema: {
          type: 'number',
        },
      },
      {
        name: 'search',
        in: 'query',
        required: false,
        schema: {
          type: 'string',
        },
      },
      {
        name: 'page',
        in: 'query',
        required: false,
        schema: {
          type: 'integer',
          minimum: 1,
        },
      },
      {
        name: 'pageSize',
        in: 'query',
        required: false,
        schema: {
          type: 'integer',
          minimum: 1,
        },
      },
      {
        name: 'maxResults',
        in: 'query',
        required: false,
        schema: {
          type: 'integer',
          minimum: 1,
        },
      },
    ],
    responses: {
      '200': {
        description: 'The operation completed successfully.',
        content: {
          'application/json': {
            schema: {
              type: 'object',
              properties: {
                data: {
                  type: 'array',
                  items: {
                    type: 'object',
                    properties: {
                      id: {
                        type: 'string',
                      },
                      userId: {
                        type: 'string',
                      },
                      createdAt: {
                        type: 'string',
                        format: 'date-time',
                      },
                      updatedAt: {
                        type: 'string',
                        format: 'date-time',
                      },
                      websiteId: {
                        type: 'string',
                      },
                      date: {
                        type: 'string',
                        format: 'date-time',
                      },
                      allDay: {
                        type: 'boolean',
                      },
                      note: {
                        type: 'string',
                      },
                    },
                    required: [
                      'id',
                      'userId',
                      'createdAt',
                      'updatedAt',
                      'websiteId',
                      'date',
                      'allDay',
                      'note',
                    ],
                  },
                },
                count: {
                  type: 'number',
                },
                page: {
                  type: 'number',
                },
                pageSize: {
                  type: 'number',
                },
                orderBy: {
                  type: 'string',
                },
                sortDescending: {
                  type: 'boolean',
                },
                search: {
                  type: 'string',
                },
                isCapped: {
                  type: 'boolean',
                },
              },
              required: ['data', 'count', 'page', 'pageSize'],
            },
          },
        },
      },
      '400': {
        description: 'Bad request.',
        content: {
          'application/json': {
            example: {
              error: {
                message: 'Bad request.',
                code: 'bad-request',
                status: 400,
              },
            },
            schema: {
              $ref: '#/components/schemas/ApiError',
            },
          },
        },
      },
      '401': {
        description: 'Unauthorized.',
        content: {
          'application/json': {
            example: {
              error: {
                message: 'Unauthorized.',
                code: 'unauthorized',
                status: 401,
              },
            },
            schema: {
              $ref: '#/components/schemas/ApiError',
            },
          },
        },
      },
    },
  } as ZodOpenApiOperationObject,
});

const operation2 = defineOperation({
  method: 'post',
  path: '/api/websites/{websiteId}/annotations',
  audience: 'public',
  auth: 'bearer',
  operation: {
    operationId: 'createWebsiteAnnotation',
    summary: 'Create or update websites website id annotations',
    tags: ['Websites'],
    parameters: [
      {
        name: 'websiteId',
        in: 'path',
        required: true,
        schema: {
          type: 'string',
        },
      },
    ],
    requestBody: {
      required: true,
      content: {
        'application/json': {
          schema: {
            type: 'object',
            properties: {
              date: {
                type: 'string',
                format: 'date-time',
              },
              allDay: {
                type: 'boolean',
              },
              note: {
                type: 'string',
                minLength: 1,
                maxLength: 500,
              },
            },
            required: ['date', 'note'],
          },
        },
      },
    },
    responses: {
      '200': {
        description: 'The operation completed successfully.',
        content: {
          'application/json': {
            schema: {
              type: 'object',
              properties: {
                id: {
                  type: 'string',
                },
                userId: {
                  type: 'string',
                },
                createdAt: {
                  type: 'string',
                  format: 'date-time',
                },
                updatedAt: {
                  type: 'string',
                  format: 'date-time',
                },
                websiteId: {
                  type: 'string',
                },
                date: {
                  type: 'string',
                  format: 'date-time',
                },
                allDay: {
                  type: 'boolean',
                },
                note: {
                  type: 'string',
                },
              },
              required: [
                'id',
                'userId',
                'createdAt',
                'updatedAt',
                'websiteId',
                'date',
                'allDay',
                'note',
              ],
            },
          },
        },
      },
      '400': {
        description: 'Bad request.',
        content: {
          'application/json': {
            example: {
              error: {
                message: 'Bad request.',
                code: 'bad-request',
                status: 400,
              },
            },
            schema: {
              $ref: '#/components/schemas/ApiError',
            },
          },
        },
      },
      '401': {
        description: 'Unauthorized.',
        content: {
          'application/json': {
            example: {
              error: {
                message: 'Unauthorized.',
                code: 'unauthorized',
                status: 401,
              },
            },
            schema: {
              $ref: '#/components/schemas/ApiError',
            },
          },
        },
      },
    },
  } as ZodOpenApiOperationObject,
});

export const operations = [operation1, operation2] as const;
