// Generated by `pnpm openapi:contracts`. Do not edit directly.

import type { ZodOpenApiOperationObject } from 'zod-openapi';
import { defineOperation } from '@/openapi/operation';

const operation1 = defineOperation({
  method: 'get',
  path: '/api/websites/{websiteId}/annotations',
  audience: 'public',
  auth: 'bearer-or-share',
  operation: {
    operationId: 'getWebsiteAnnotations',
    summary: 'Get websites website id annotations',
    description:
      'Returns a paginated list of dated notes for the website, optionally filtered by date range or search text.',
    tags: ['Websites'],
    parameters: [
      {
        name: 'websiteId',
        in: 'path',
        required: true,
        schema: {
          type: 'string',
        },
        description: 'ID of the website.',
      },
      {
        name: 'startAt',
        in: 'query',
        required: false,
        schema: {
          type: 'integer',
        },
        description: 'Start of the date range as a Unix timestamp in milliseconds.',
      },
      {
        name: 'endAt',
        in: 'query',
        required: false,
        schema: {
          type: 'integer',
        },
        description: 'End of the date range as a Unix timestamp in milliseconds.',
      },
      {
        name: 'search',
        in: 'query',
        required: false,
        schema: {
          type: 'string',
        },
        description: 'Search text used to filter results.',
      },
      {
        name: 'page',
        in: 'query',
        required: false,
        schema: {
          type: 'integer',
          minimum: 1,
        },
        description: 'Page number, starting at 1.',
      },
      {
        name: 'pageSize',
        in: 'query',
        required: false,
        schema: {
          type: 'integer',
          minimum: 1,
        },
        description: 'Number of results per page.',
      },
      {
        name: 'maxResults',
        in: 'query',
        required: false,
        schema: {
          type: 'integer',
          minimum: 1,
        },
        description: 'Maximum number of results to include.',
      },
      {
        name: 'period',
        in: 'query',
        required: false,
        schema: {
          type: 'string',
          enum: [
            'today',
            '24h',
            '7d',
            '30d',
            '0day',
            '24hour',
            '0week',
            '7day',
            '0month',
            '30day',
            '90day',
            '0year',
            '6month',
            '12month',
          ],
        },
        description:
          'Relative date range, for example 7d or 30day, used instead of an explicit startAt/endAt range.',
      },
    ],
    responses: {
      '200': {
        description: 'The operation completed successfully.',
        content: {
          'application/json': {
            schema: {
              type: 'object',
              properties: {
                data: {
                  type: 'array',
                  items: {
                    type: 'object',
                    properties: {
                      id: {
                        type: 'string',
                        description: 'Unique identifier of the resource.',
                      },
                      userId: {
                        type: 'string',
                        description: 'ID of the associated user.',
                      },
                      createdAt: {
                        type: 'string',
                        format: 'date-time',
                        description: 'Date and time the record was created.',
                      },
                      updatedAt: {
                        type: 'string',
                        format: 'date-time',
                        description: 'Date and time the record was last updated.',
                      },
                      websiteId: {
                        type: 'string',
                        description: 'ID of the website.',
                      },
                      date: {
                        type: 'string',
                        format: 'date-time',
                      },
                      allDay: {
                        type: 'boolean',
                        description: 'Whether the annotation applies to the entire day.',
                      },
                      note: {
                        type: 'string',
                        description: 'Text of the annotation.',
                      },
                    },
                    required: [
                      'id',
                      'userId',
                      'createdAt',
                      'updatedAt',
                      'websiteId',
                      'date',
                      'allDay',
                      'note',
                    ],
                  },
                  description: 'Data returned by the operation.',
                },
                count: {
                  type: 'number',
                  description: 'Number of matching records.',
                },
                page: {
                  type: 'number',
                  description: 'Page number, starting at 1.',
                },
                pageSize: {
                  type: 'number',
                  description: 'Number of results per page.',
                },
                orderBy: {
                  type: 'string',
                  description: 'Field to sort the results by.',
                },
                sortDescending: {
                  type: 'boolean',
                  description: 'Whether to sort results in descending order.',
                },
                search: {
                  type: 'string',
                  description: 'Search text used to filter results.',
                },
                isCapped: {
                  type: 'boolean',
                  description: 'Whether the results were truncated by the maximum result limit.',
                },
              },
              required: ['data', 'count', 'page', 'pageSize'],
            },
          },
        },
      },
      '400': {
        description: 'Bad request.',
        content: {
          'application/json': {
            example: {
              error: {
                message: 'Bad request.',
                code: 'bad-request',
                status: 400,
              },
            },
            schema: {
              $ref: '#/components/schemas/ApiError',
            },
          },
        },
      },
      '401': {
        description: 'Unauthorized.',
        content: {
          'application/json': {
            example: {
              error: {
                message: 'Unauthorized.',
                code: 'unauthorized',
                status: 401,
              },
            },
            schema: {
              $ref: '#/components/schemas/ApiError',
            },
          },
        },
      },
    },
  } as ZodOpenApiOperationObject,
});

const operation2 = defineOperation({
  method: 'post',
  path: '/api/websites/{websiteId}/annotations',
  audience: 'public',
  auth: 'bearer',
  operation: {
    operationId: 'createWebsiteAnnotation',
    summary: 'Create or update websites website id annotations',
    description:
      'Adds a dated note to the website, optionally marking it as an all-day annotation.',
    tags: ['Websites'],
    parameters: [
      {
        name: 'websiteId',
        in: 'path',
        required: true,
        schema: {
          type: 'string',
        },
        description: 'ID of the website.',
      },
    ],
    requestBody: {
      required: true,
      content: {
        'application/json': {
          schema: {
            type: 'object',
            properties: {
              date: {
                type: 'string',
                format: 'date-time',
              },
              allDay: {
                type: 'boolean',
                description: 'Whether the annotation applies to the entire day.',
              },
              note: {
                type: 'string',
                minLength: 1,
                maxLength: 500,
                description: 'Text of the annotation.',
              },
            },
            required: ['date', 'note'],
          },
        },
      },
    },
    responses: {
      '200': {
        description: 'The operation completed successfully.',
        content: {
          'application/json': {
            schema: {
              type: 'object',
              properties: {
                id: {
                  type: 'string',
                  description: 'Unique identifier of the resource.',
                },
                userId: {
                  type: 'string',
                  description: 'ID of the associated user.',
                },
                createdAt: {
                  type: 'string',
                  format: 'date-time',
                  description: 'Date and time the record was created.',
                },
                updatedAt: {
                  type: 'string',
                  format: 'date-time',
                  description: 'Date and time the record was last updated.',
                },
                websiteId: {
                  type: 'string',
                  description: 'ID of the website.',
                },
                date: {
                  type: 'string',
                  format: 'date-time',
                },
                allDay: {
                  type: 'boolean',
                  description: 'Whether the annotation applies to the entire day.',
                },
                note: {
                  type: 'string',
                  description: 'Text of the annotation.',
                },
              },
              required: [
                'id',
                'userId',
                'createdAt',
                'updatedAt',
                'websiteId',
                'date',
                'allDay',
                'note',
              ],
            },
          },
        },
      },
      '400': {
        description: 'Bad request.',
        content: {
          'application/json': {
            example: {
              error: {
                message: 'Bad request.',
                code: 'bad-request',
                status: 400,
              },
            },
            schema: {
              $ref: '#/components/schemas/ApiError',
            },
          },
        },
      },
      '401': {
        description: 'Unauthorized.',
        content: {
          'application/json': {
            example: {
              error: {
                message: 'Unauthorized.',
                code: 'unauthorized',
                status: 401,
              },
            },
            schema: {
              $ref: '#/components/schemas/ApiError',
            },
          },
        },
      },
    },
  } as ZodOpenApiOperationObject,
});

export const operations = [operation1, operation2] as const;
