// Generated by `pnpm openapi:contracts`. Do not edit directly.

import type { ZodOpenApiOperationObject } from 'zod-openapi';
import { defineOperation } from '@/openapi/operation';

const operation1 = defineOperation({
  method: 'get',
  path: '/api/websites/{websiteId}/active',
  audience: 'public',
  auth: 'bearer-or-share',
  operation: {
    operationId: 'getWebsitesWebsiteIdActive',
    summary: 'Get websites website id active',
    description:
      'Get websites website id active. The request and response models are derived from the validated route contract.',
    tags: ['Websites'],
    parameters: [
      {
        name: 'websiteId',
        in: 'path',
        required: true,
        schema: {
          type: 'string',
        },
      },
    ],
    responses: {
      '200': {
        description: 'The operation completed successfully.',
        content: {
          'application/json': {
            schema: {
              type: 'object',
              properties: {
                visitors: {
                  type: 'number',
                },
              },
              required: ['visitors'],
            },
          },
        },
      },
      '401': {
        description: 'Unauthorized.',
        content: {
          'application/json': {
            example: {
              error: {
                message: 'Unauthorized.',
                code: 'unauthorized',
                status: 401,
              },
            },
            schema: {
              $ref: '#/components/schemas/ApiError',
            },
          },
        },
      },
    },
  } as ZodOpenApiOperationObject,
});

export const operations = [operation1] as const;
