// Generated by `pnpm openapi:contracts`. Do not edit directly.

import type { ZodOpenApiOperationObject } from 'zod-openapi';
import { defineOperation } from '@/openapi/operation';

const operation1 = defineOperation({
  method: 'post',
  path: '/api/boards/{boardId}/clone',
  audience: 'public',
  auth: 'bearer-or-share',
  operation: {
    operationId: 'postBoardsBoardIdClone',
    summary: 'Create or update boards board id clone',
    description:
      'Create or update boards board id clone. The request and response models are derived from the validated route contract.',
    tags: ['Boards'],
    parameters: [
      {
        name: 'boardId',
        in: 'path',
        required: true,
        schema: {
          type: 'string',
        },
      },
    ],
    requestBody: {
      required: true,
      content: {
        'application/json': {
          schema: {
            type: 'object',
            properties: {
              name: {
                type: 'string',
                maxLength: 200,
              },
              description: {
                type: 'string',
                maxLength: 500,
              },
              parameters: {
                type: 'object',
                properties: {},
              },
            },
          },
        },
      },
    },
    responses: {
      '200': {
        description: 'The operation completed successfully.',
        content: {
          'application/json': {
            schema: {
              type: 'object',
              properties: {
                id: {
                  type: 'string',
                },
                userId: {
                  type: 'string',
                },
                createdAt: {
                  type: 'string',
                  format: 'date-time',
                },
                updatedAt: {
                  type: 'string',
                  format: 'date-time',
                },
                name: {
                  type: 'string',
                },
                teamId: {
                  type: 'string',
                },
                type: {
                  type: 'string',
                },
                description: {
                  type: 'string',
                },
                parameters: {
                  anyOf: [
                    {
                      type: 'string',
                    },
                    {
                      type: 'number',
                    },
                    {
                      const: false,
                    },
                    {
                      const: true,
                    },
                    {
                      type: 'object',
                      properties: {},
                      additionalProperties: {
                        anyOf: [
                          {
                            type: 'string',
                          },
                          {
                            type: 'number',
                          },
                          {
                            const: false,
                          },
                          {
                            const: true,
                          },
                          {},
                          {
                            type: 'object',
                            properties: {
                              length: {
                                type: 'number',
                              },
                            },
                            required: ['length'],
                          },
                        ],
                      },
                    },
                    {
                      type: 'object',
                      properties: {
                        length: {
                          type: 'number',
                        },
                      },
                      required: ['length'],
                    },
                  ],
                },
              },
              required: [
                'id',
                'userId',
                'createdAt',
                'updatedAt',
                'name',
                'teamId',
                'type',
                'description',
                'parameters',
              ],
            },
          },
        },
      },
      '400': {
        description: 'Bad request.',
        content: {
          'application/json': {
            example: {
              error: {
                message: 'Bad request.',
                code: 'bad-request',
                status: 400,
              },
            },
            schema: {
              $ref: '#/components/schemas/ApiError',
            },
          },
        },
      },
      '401': {
        description: 'Unauthorized.',
        content: {
          'application/json': {
            example: {
              error: {
                message: 'Unauthorized.',
                code: 'unauthorized',
                status: 401,
              },
            },
            schema: {
              $ref: '#/components/schemas/ApiError',
            },
          },
        },
      },
    },
  } as ZodOpenApiOperationObject,
});

export const operations = [operation1] as const;
