import {
  arSA,
  cs,
  sk,
  da,
  de,
  el,
  enUS,
  enGB,
  es,
  fi,
  fr,
  faIR,
  he,
  hi,
  id,
  it,
  ja,
  ko,
  mn,
  ms,
  nb,
  nl,
  pl,
  pt,
  ptBR,
  ro,
  ru,
  sl,
  sv,
  ta,
  tr,
  uk,
  zhCN,
  zhTW,
  ca,
  hu,
} from 'date-fns/locale';

export const languages = {
  'ar-SA': { label: 'العربية', display: 'ar' },
  'zh-CN': { label: '中文', display: 'cn' },
  'zh-TW': { label: '中文(繁體)', display: 'tw' },
  'ca-ES': { label: 'Català', display: 'ca' },
  'cs-CZ': { label: 'Čeština', display: 'cs' },
  'da-DK': { label: 'Dansk', display: 'da' },
  'de-DE': { label: 'Deutsch', display: 'de' },
  'en-US': { label: 'English (US)', display: 'en' },
  'en-GB': { label: 'English (UK)', display: 'en-GB'},
  'es-MX': { label: 'Español', display: 'es' },
  'fa-IR': { label: 'فارسی', display: 'fa' },
  'fo-FO': { label: 'Føroyskt', display: 'fo' },
  'fr-FR': { label: 'Français', display: 'fr' },
  'el-GR': { label: 'Ελληνικά', display: 'el' },
  'he-IL': { label: 'עברית', display: 'he' },
  'hi-IN': { label: 'हिन्दी', display: 'hi' },
  'hu-HU': { label: 'Hungarian', display: 'hu' },
  'it-IT': { label: 'Italiano', display: 'it' },
  'id-ID': { label: 'Bahasa Indonesia', display: 'id' },
  'ja-JP': { label: '日本語', display: 'ja' },
  'ko-KR': { label: '한국어', display: 'ko' },
  'ms-MY': { label: 'Malay', display: 'ms' },
  'mn-MN': { label: 'Монгол', display: 'mn' },
  'nl-NL': { label: 'Nederlands', display: 'nl' },
  'nb-NO': { label: 'Norsk Bokmål', display: 'nb' },
  'pl-PL': { label: 'Polski', display: 'pl' },
  'pt-PT': { label: 'Português', display: 'pt' },
  'pt-BR': { label: 'Português do Brasil', display: 'pt-BR' },
  'ru-RU': { label: 'Русский', display: 'ru' },
  'ro-RO': { label: 'Română', display: 'ro' },
  'sk-SK': { label: 'Slovenčina', display: 'sk' },
  'sl-SI': { label: 'Slovenščina', display: 'sl' },
  'fi-FI': { label: 'Suomi', display: 'fi' },
  'sv-SE': { label: 'Svenska', display: 'sv' },
  'ta-IN': { label: 'தமிழ்', display: 'ta' },
  'tr-TR': { label: 'Türkçe', display: 'tr' },
  'uk-UA': { label: 'українська', display: 'uk' },
};

export const rtlLocales = ['ar-SA', 'fa-IR'];

export const dateLocales = {
  'ar-SA': arSA,
  'en-US': enUS,
  'en-GB': enGB,
  'nl-NL': nl,
  'zh-CN': zhCN,
  'zh-TW': zhTW,
  'de-DE': de,
  'da-DK': da,
  'ru-RU': ru,
  'sv-SE': sv,
  'tr-TR': tr,
  'ja-JP': ja,
  'es-MX': es,
  'fr-FR': fr,
  'mn-MN': mn,
  'el-GR': el,
  'fo-FO': da,
  'pt-PT': pt,
  'pt-BR': ptBR,
  'ro-RO': ro,
  'nb-NO': nb,
  'id-ID': id,
  'uk-UA': uk,
  'fi-FI': fi,
  'cs-CZ': cs,
  'sk-SK': sk,
  'pl-PL': pl,
  'ta-In': ta,
  'hi-IN': hi,
  'he-IL': he,
  'it-IT': it,
  'fa-IR': faIR,
  'ms-MY': ms,
  'ca-ES': ca,
  'hu-HU': hu,
  'ko-KR': ko,
  'sl-SI': sl,
};
