// Generated by `pnpm openapi:contracts`. Do not edit directly.

import type { ZodOpenApiOperationObject } from 'zod-openapi';
import { defineOperation } from '@/openapi/operation';

const operation1 = defineOperation({
  method: 'post',
  path: '/api/reports/revenue',
  audience: 'public',
  auth: 'bearer-or-share',
  operation: {
    operationId: 'postReportsRevenue',
    summary: 'Create or update reports revenue',
    tags: ['Reports'],
    requestBody: {
      required: true,
      content: {
        'application/json': {
          schema: {
            type: 'object',
            properties: {
              websiteId: {
                type: 'string',
                format: 'uuid',
              },
              filters: {
                type: 'object',
                additionalProperties: true,
              },
              type: {
                type: 'string',
              },
              parameters: {
                type: 'object',
                additionalProperties: true,
              },
            },
            required: ['websiteId', 'filters', 'type', 'parameters'],
          },
        },
      },
    },
    responses: {
      '200': {
        description: 'The operation completed successfully.',
        content: {
          'application/json': {
            schema: {
              type: 'object',
              properties: {
                chart: {
                  type: 'array',
                  items: {
                    type: 'object',
                    properties: {
                      x: {
                        type: 'string',
                      },
                      t: {
                        type: 'string',
                      },
                      y: {
                        type: 'number',
                      },
                      count: {
                        type: 'number',
                      },
                    },
                    required: ['x', 't', 'y', 'count'],
                  },
                },
                total: {},
                country: {
                  type: 'array',
                  items: {
                    type: 'object',
                    properties: {
                      name: {
                        type: 'string',
                      },
                      value: {
                        type: 'number',
                      },
                    },
                    required: ['name', 'value'],
                  },
                },
                region: {
                  type: 'array',
                  items: {
                    type: 'object',
                    properties: {
                      name: {
                        type: 'string',
                      },
                      value: {
                        type: 'number',
                      },
                      country: {
                        type: 'string',
                      },
                    },
                    required: ['name', 'value', 'country'],
                  },
                },
                referrer: {
                  type: 'array',
                  items: {
                    type: 'object',
                    properties: {
                      name: {
                        type: 'string',
                      },
                      value: {
                        type: 'number',
                      },
                    },
                    required: ['name', 'value'],
                  },
                },
                channel: {
                  type: 'array',
                  items: {
                    type: 'object',
                    properties: {
                      name: {
                        type: 'string',
                      },
                      value: {
                        type: 'number',
                      },
                    },
                    required: ['name', 'value'],
                  },
                },
              },
              required: ['chart', 'total', 'country', 'region', 'referrer', 'channel'],
            },
          },
        },
      },
      '400': {
        description: 'Bad request.',
        content: {
          'application/json': {
            example: {
              error: {
                message: 'Bad request.',
                code: 'bad-request',
                status: 400,
              },
            },
            schema: {
              $ref: '#/components/schemas/ApiError',
            },
          },
        },
      },
      '401': {
        description: 'Unauthorized.',
        content: {
          'application/json': {
            example: {
              error: {
                message: 'Unauthorized.',
                code: 'unauthorized',
                status: 401,
              },
            },
            schema: {
              $ref: '#/components/schemas/ApiError',
            },
          },
        },
      },
    },
  } as ZodOpenApiOperationObject,
});

export const operations = [operation1] as const;
