// Generated by `pnpm openapi:contracts`. Do not edit directly.

import type { ZodOpenApiOperationObject } from 'zod-openapi';
import { defineOperation } from '@/openapi/operation';

const operation1 = defineOperation({
  method: 'get',
  path: '/api/teams',
  audience: 'public',
  auth: 'bearer',
  operation: {
    operationId: 'getTeams',
    summary: 'Get teams',
    tags: ['Teams'],
    parameters: [
      {
        name: 'page',
        in: 'query',
        required: false,
        schema: {
          type: 'integer',
          minimum: 1,
        },
      },
      {
        name: 'pageSize',
        in: 'query',
        required: false,
        schema: {
          type: 'integer',
          minimum: 1,
        },
      },
      {
        name: 'maxResults',
        in: 'query',
        required: false,
        schema: {
          type: 'integer',
          minimum: 1,
        },
      },
      {
        name: 'orderBy',
        in: 'query',
        required: false,
        schema: {
          type: 'string',
        },
      },
      {
        name: 'sortDescending',
        in: 'query',
        required: false,
        schema: {
          type: 'string',
          enum: ['true', 'false'],
        },
      },
    ],
    responses: {
      '200': {
        description: 'The operation completed successfully.',
        content: {
          'application/json': {
            schema: {
              type: 'object',
              properties: {
                data: {
                  type: 'array',
                  items: {
                    type: 'object',
                    properties: {
                      id: {
                        type: 'string',
                      },
                      createdAt: {
                        type: 'string',
                        format: 'date-time',
                      },
                      updatedAt: {
                        type: 'string',
                        format: 'date-time',
                      },
                      logoUrl: {
                        type: 'string',
                      },
                      twoFactorRequired: {
                        type: 'boolean',
                      },
                      deletedAt: {
                        type: 'string',
                        format: 'date-time',
                      },
                      name: {
                        type: 'string',
                      },
                      accessCode: {
                        type: 'string',
                      },
                    },
                    required: [
                      'id',
                      'createdAt',
                      'updatedAt',
                      'logoUrl',
                      'twoFactorRequired',
                      'deletedAt',
                      'name',
                      'accessCode',
                    ],
                  },
                },
                count: {
                  type: 'number',
                },
                page: {
                  type: 'number',
                },
                pageSize: {
                  type: 'number',
                },
                orderBy: {
                  type: 'string',
                },
                sortDescending: {
                  type: 'boolean',
                },
                search: {
                  type: 'string',
                },
                isCapped: {
                  type: 'boolean',
                },
              },
              required: ['data', 'count', 'page', 'pageSize'],
            },
          },
        },
      },
      '400': {
        description: 'Bad request.',
        content: {
          'application/json': {
            example: {
              error: {
                message: 'Bad request.',
                code: 'bad-request',
                status: 400,
              },
            },
            schema: {
              $ref: '#/components/schemas/ApiError',
            },
          },
        },
      },
      '401': {
        description: 'Unauthorized.',
        content: {
          'application/json': {
            example: {
              error: {
                message: 'Unauthorized.',
                code: 'unauthorized',
                status: 401,
              },
            },
            schema: {
              $ref: '#/components/schemas/ApiError',
            },
          },
        },
      },
    },
  } as ZodOpenApiOperationObject,
});

const operation2 = defineOperation({
  method: 'post',
  path: '/api/teams',
  audience: 'public',
  auth: 'bearer',
  operation: {
    operationId: 'postTeams',
    summary: 'Create or update teams',
    tags: ['Teams'],
    requestBody: {
      required: true,
      content: {
        'application/json': {
          schema: {
            type: 'object',
            properties: {
              name: {
                type: 'string',
                maxLength: 50,
              },
              ownerId: {
                type: 'string',
                format: 'uuid',
              },
            },
            required: ['name'],
          },
        },
      },
    },
    responses: {
      '200': {
        description: 'The operation completed successfully.',
        content: {
          'application/json': {
            schema: {
              type: 'array',
              prefixItems: [
                {
                  type: 'object',
                  properties: {
                    id: {
                      type: 'string',
                    },
                    createdAt: {
                      type: 'string',
                      format: 'date-time',
                    },
                    updatedAt: {
                      type: 'string',
                      format: 'date-time',
                    },
                    logoUrl: {
                      type: 'string',
                    },
                    twoFactorRequired: {
                      type: 'boolean',
                    },
                    deletedAt: {
                      type: 'string',
                      format: 'date-time',
                    },
                    name: {
                      type: 'string',
                    },
                    accessCode: {
                      type: 'string',
                    },
                  },
                  required: [
                    'id',
                    'createdAt',
                    'updatedAt',
                    'logoUrl',
                    'twoFactorRequired',
                    'deletedAt',
                    'name',
                    'accessCode',
                  ],
                },
                {
                  type: 'object',
                  properties: {
                    id: {
                      type: 'string',
                    },
                    userId: {
                      type: 'string',
                    },
                    createdAt: {
                      type: 'string',
                      format: 'date-time',
                    },
                    updatedAt: {
                      type: 'string',
                      format: 'date-time',
                    },
                    role: {
                      type: 'string',
                    },
                    teamId: {
                      type: 'string',
                    },
                  },
                  required: ['id', 'userId', 'createdAt', 'updatedAt', 'role', 'teamId'],
                },
              ],
              minItems: 2,
              maxItems: 2,
            },
          },
        },
      },
      '400': {
        description: 'Bad request.',
        content: {
          'application/json': {
            example: {
              error: {
                message: 'Bad request.',
                code: 'bad-request',
                status: 400,
              },
            },
            schema: {
              $ref: '#/components/schemas/ApiError',
            },
          },
        },
      },
      '401': {
        description: 'Unauthorized.',
        content: {
          'application/json': {
            example: {
              error: {
                message: 'Unauthorized.',
                code: 'unauthorized',
                status: 401,
              },
            },
            schema: {
              $ref: '#/components/schemas/ApiError',
            },
          },
        },
      },
    },
  } as ZodOpenApiOperationObject,
});

export const operations = [operation1, operation2] as const;
