// Generated by `pnpm openapi:contracts`. Do not edit directly.

import type { ZodOpenApiOperationObject } from 'zod-openapi';
import { defineOperation } from '@/openapi/operation';

const operation1 = defineOperation({
  method: 'post',
  path: '/api/reports/goal',
  audience: 'public',
  auth: 'bearer-or-share',
  operation: {
    operationId: 'postReportsGoal',
    summary: 'Create or update reports goal',
    tags: ['Reports'],
    requestBody: {
      required: true,
      content: {
        'application/json': {
          schema: {
            type: 'object',
            properties: {
              websiteId: {
                type: 'string',
                format: 'uuid',
              },
              filters: {
                type: 'object',
                additionalProperties: true,
              },
              type: {
                type: 'string',
              },
              parameters: {
                type: 'object',
                additionalProperties: true,
              },
            },
            required: ['websiteId', 'filters', 'type', 'parameters'],
          },
        },
      },
    },
    responses: {
      '200': {
        description: 'The operation completed successfully.',
        content: {
          'application/json': {
            schema: {
              type: 'object',
              properties: {
                num: {
                  type: 'number',
                },
                total: {
                  type: 'number',
                },
              },
              required: ['num', 'total'],
            },
          },
        },
      },
      '400': {
        description: 'Bad request.',
        content: {
          'application/json': {
            example: {
              error: {
                message: 'Bad request.',
                code: 'bad-request',
                status: 400,
              },
            },
            schema: {
              $ref: '#/components/schemas/ApiError',
            },
          },
        },
      },
      '401': {
        description: 'Unauthorized.',
        content: {
          'application/json': {
            example: {
              error: {
                message: 'Unauthorized.',
                code: 'unauthorized',
                status: 401,
              },
            },
            schema: {
              $ref: '#/components/schemas/ApiError',
            },
          },
        },
      },
    },
  } as ZodOpenApiOperationObject,
});

export const operations = [operation1] as const;
