// Generated by `pnpm openapi:contracts`. Do not edit directly.

import type { ZodOpenApiOperationObject } from 'zod-openapi';
import { defineOperation } from '@/openapi/operation';

const operation1 = defineOperation({
  method: 'get',
  path: '/api/websites/{websiteId}/values',
  audience: 'public',
  auth: 'bearer-or-share',
  operation: {
    operationId: 'getWebsitesWebsiteIdValues',
    summary: 'Get websites website id values',
    tags: ['Websites'],
    parameters: [
      {
        name: 'websiteId',
        in: 'path',
        required: true,
        schema: {
          type: 'string',
        },
      },
      {
        name: 'startAt',
        in: 'query',
        required: false,
        schema: {
          type: 'number',
        },
      },
      {
        name: 'endAt',
        in: 'query',
        required: false,
        schema: {
          type: 'number',
        },
      },
      {
        name: 'startDate',
        in: 'query',
        required: false,
        schema: {
          type: 'string',
          format: 'date-time',
        },
      },
      {
        name: 'endDate',
        in: 'query',
        required: false,
        schema: {
          type: 'string',
          format: 'date-time',
        },
      },
      {
        name: 'timezone',
        in: 'query',
        required: false,
        schema: {
          type: 'string',
        },
      },
      {
        name: 'unit',
        in: 'query',
        required: false,
        schema: {
          type: 'string',
        },
      },
      {
        name: 'compare',
        in: 'query',
        required: false,
        schema: {
          type: 'string',
          enum: ['prev', 'yoy'],
        },
      },
      {
        name: 'type',
        in: 'query',
        required: true,
        schema: {
          type: 'string',
        },
      },
      {
        name: 'search',
        in: 'query',
        required: false,
        schema: {
          type: 'string',
        },
      },
    ],
    responses: {
      '200': {
        description: 'The operation completed successfully.',
        content: {
          'application/json': {
            schema: {
              type: 'array',
              items: {},
            },
          },
        },
      },
      '400': {
        description: 'Bad request.',
        content: {
          'application/json': {
            example: {
              error: {
                message: 'Bad request.',
                code: 'bad-request',
                status: 400,
              },
            },
            schema: {
              $ref: '#/components/schemas/ApiError',
            },
          },
        },
      },
      '401': {
        description: 'Unauthorized.',
        content: {
          'application/json': {
            example: {
              error: {
                message: 'Unauthorized.',
                code: 'unauthorized',
                status: 401,
              },
            },
            schema: {
              $ref: '#/components/schemas/ApiError',
            },
          },
        },
      },
    },
  } as ZodOpenApiOperationObject,
});

export const operations = [operation1] as const;
