// Generated by `pnpm openapi:contracts`. Do not edit directly.

import type { ZodOpenApiOperationObject } from 'zod-openapi';
import { defineOperation } from '@/openapi/operation';

const operation1 = defineOperation({
  method: 'get',
  path: '/api/scripts/telemetry',
  audience: 'internal',
  auth: 'none',
  operation: {
    operationId: 'getScriptsTelemetry',
    summary: 'Get scripts telemetry',
    tags: ['Scripts'],
    responses: {
      '200': {
        description:
          'Successful response. The response shape is inferred as free-form because the handler does not expose a reusable response schema.',
        content: {
          'text/javascript': {
            schema: {
              type: 'string',
            },
          },
        },
      },
    },
  } as ZodOpenApiOperationObject,
});

export const operations = [operation1] as const;
