// Generated by `pnpm openapi:contracts`. Do not edit directly.

import type { ZodOpenApiOperationObject } from 'zod-openapi';
import { defineOperation } from '@/openapi/operation';

const operation1 = defineOperation({
  method: 'get',
  path: '/api/websites/{websiteId}/replays',
  audience: 'public',
  auth: 'bearer-or-share',
  operation: {
    operationId: 'getWebsitesWebsiteIdReplays',
    summary: 'Get websites website id replays',
    description:
      'Get websites website id replays. The request and response models are derived from the validated route contract.',
    tags: ['Websites'],
    parameters: [
      {
        name: 'websiteId',
        in: 'path',
        required: true,
        schema: {
          type: 'string',
        },
      },
      {
        name: 'startAt',
        in: 'query',
        required: false,
        schema: {
          type: 'number',
        },
      },
      {
        name: 'endAt',
        in: 'query',
        required: false,
        schema: {
          type: 'number',
        },
      },
      {
        name: 'startDate',
        in: 'query',
        required: false,
        schema: {
          type: 'string',
          format: 'date-time',
        },
      },
      {
        name: 'endDate',
        in: 'query',
        required: false,
        schema: {
          type: 'string',
          format: 'date-time',
        },
      },
      {
        name: 'timezone',
        in: 'query',
        required: false,
        schema: {
          type: 'string',
        },
      },
      {
        name: 'unit',
        in: 'query',
        required: false,
        schema: {
          type: 'string',
        },
      },
      {
        name: 'compare',
        in: 'query',
        required: false,
        schema: {
          type: 'string',
          enum: ['prev', 'yoy'],
        },
      },
      {
        name: 'path',
        in: 'query',
        required: false,
        schema: {
          type: 'string',
        },
      },
      {
        name: 'referrer',
        in: 'query',
        required: false,
        schema: {
          type: 'string',
        },
      },
      {
        name: 'title',
        in: 'query',
        required: false,
        schema: {
          type: 'string',
        },
      },
      {
        name: 'query',
        in: 'query',
        required: false,
        schema: {
          type: 'string',
        },
      },
      {
        name: 'os',
        in: 'query',
        required: false,
        schema: {
          type: 'string',
        },
      },
      {
        name: 'browser',
        in: 'query',
        required: false,
        schema: {
          type: 'string',
        },
      },
      {
        name: 'device',
        in: 'query',
        required: false,
        schema: {
          type: 'string',
        },
      },
      {
        name: 'country',
        in: 'query',
        required: false,
        schema: {
          type: 'string',
        },
      },
      {
        name: 'region',
        in: 'query',
        required: false,
        schema: {
          type: 'string',
        },
      },
      {
        name: 'city',
        in: 'query',
        required: false,
        schema: {
          type: 'string',
        },
      },
      {
        name: 'tag',
        in: 'query',
        required: false,
        schema: {
          type: 'string',
        },
      },
      {
        name: 'hostname',
        in: 'query',
        required: false,
        schema: {
          type: 'string',
        },
      },
      {
        name: 'distinctId',
        in: 'query',
        required: false,
        schema: {
          type: 'string',
        },
      },
      {
        name: 'language',
        in: 'query',
        required: false,
        schema: {
          type: 'string',
        },
      },
      {
        name: 'event',
        in: 'query',
        required: false,
        schema: {
          type: 'string',
        },
      },
      {
        name: 'utmSource',
        in: 'query',
        required: false,
        schema: {
          type: 'string',
        },
      },
      {
        name: 'utmMedium',
        in: 'query',
        required: false,
        schema: {
          type: 'string',
        },
      },
      {
        name: 'utmCampaign',
        in: 'query',
        required: false,
        schema: {
          type: 'string',
        },
      },
      {
        name: 'utmContent',
        in: 'query',
        required: false,
        schema: {
          type: 'string',
        },
      },
      {
        name: 'utmTerm',
        in: 'query',
        required: false,
        schema: {
          type: 'string',
        },
      },
      {
        name: 'excludeBounce',
        in: 'query',
        required: false,
        schema: {
          type: 'string',
        },
      },
      {
        name: 'segment',
        in: 'query',
        required: false,
        schema: {
          type: 'string',
          format: 'uuid',
        },
      },
      {
        name: 'cohort',
        in: 'query',
        required: false,
        schema: {
          type: 'string',
          format: 'uuid',
        },
      },
      {
        name: 'eventType',
        in: 'query',
        required: false,
        schema: {
          type: 'integer',
          minimum: 1,
        },
      },
      {
        name: 'match',
        in: 'query',
        required: false,
        schema: {
          type: 'string',
          enum: ['all', 'any'],
        },
      },
      {
        name: 'minDuration',
        in: 'query',
        required: false,
        schema: {
          type: 'integer',
          minimum: 0,
        },
      },
      {
        name: 'page',
        in: 'query',
        required: false,
        schema: {
          type: 'integer',
          minimum: 1,
        },
      },
      {
        name: 'pageSize',
        in: 'query',
        required: false,
        schema: {
          type: 'integer',
          minimum: 1,
        },
      },
      {
        name: 'maxResults',
        in: 'query',
        required: false,
        schema: {
          type: 'integer',
          minimum: 1,
        },
      },
      {
        name: 'search',
        in: 'query',
        required: false,
        schema: {
          type: 'string',
        },
      },
    ],
    responses: {
      '200': {
        description: 'The operation completed successfully.',
        content: {
          'application/json': {
            schema: {
              type: 'object',
              properties: {
                data: {
                  type: 'array',
                  items: {
                    type: 'object',
                    properties: {
                      id: {
                        type: 'string',
                      },
                      sessionId: {
                        type: 'string',
                      },
                      websiteId: {
                        type: 'string',
                      },
                      browser: {
                        type: 'string',
                      },
                      os: {
                        type: 'string',
                      },
                      device: {
                        type: 'string',
                      },
                      country: {
                        type: 'string',
                      },
                      city: {
                        type: 'string',
                      },
                      eventCount: {
                        type: 'number',
                      },
                      chunkCount: {
                        type: 'number',
                      },
                      startedAt: {
                        anyOf: [
                          {
                            type: 'string',
                          },
                          {
                            type: 'string',
                            format: 'date-time',
                          },
                        ],
                      },
                      endedAt: {
                        anyOf: [
                          {
                            type: 'string',
                          },
                          {
                            type: 'string',
                            format: 'date-time',
                          },
                        ],
                      },
                      duration: {
                        type: 'number',
                      },
                      createdAt: {
                        anyOf: [
                          {
                            type: 'string',
                          },
                          {
                            type: 'string',
                            format: 'date-time',
                          },
                        ],
                      },
                    },
                    required: [
                      'id',
                      'sessionId',
                      'websiteId',
                      'browser',
                      'os',
                      'device',
                      'country',
                      'city',
                      'eventCount',
                      'chunkCount',
                      'startedAt',
                      'endedAt',
                      'duration',
                      'createdAt',
                    ],
                  },
                },
                count: {
                  type: 'number',
                },
                page: {
                  type: 'number',
                },
                pageSize: {
                  type: 'number',
                },
                orderBy: {
                  type: 'string',
                },
                sortDescending: {
                  type: 'boolean',
                },
                search: {
                  type: 'string',
                },
                isCapped: {
                  type: 'boolean',
                },
              },
              required: ['data', 'count', 'page', 'pageSize'],
            },
          },
        },
      },
      '400': {
        description: 'Bad request.',
        content: {
          'application/json': {
            example: {
              error: {
                message: 'Bad request.',
                code: 'bad-request',
                status: 400,
              },
            },
            schema: {
              $ref: '#/components/schemas/ApiError',
            },
          },
        },
      },
      '401': {
        description: 'Unauthorized.',
        content: {
          'application/json': {
            example: {
              error: {
                message: 'Unauthorized.',
                code: 'unauthorized',
                status: 401,
              },
            },
            schema: {
              $ref: '#/components/schemas/ApiError',
            },
          },
        },
      },
    },
  } as ZodOpenApiOperationObject,
});

export const operations = [operation1] as const;
