// Generated by `pnpm openapi:contracts`. Do not edit directly.

import type { ZodOpenApiOperationObject } from 'zod-openapi';
import { defineOperation } from '@/openapi/operation';

const operation1 = defineOperation({
  method: 'delete',
  path: '/api/websites/{websiteId}/segments/{segmentId}',
  audience: 'public',
  auth: 'bearer',
  operation: {
    operationId: 'deleteWebsiteSegment',
    summary: 'Delete websites website id segments segment id',
    description: 'Deletes the specified saved segment or cohort from the website.',
    tags: ['Websites'],
    parameters: [
      {
        name: 'websiteId',
        in: 'path',
        required: true,
        schema: {
          type: 'string',
        },
        description: 'ID of the website.',
      },
      {
        name: 'segmentId',
        in: 'path',
        required: true,
        schema: {
          type: 'string',
        },
        description: 'ID of the saved segment or cohort.',
      },
    ],
    responses: {
      '200': {
        description: 'The operation completed successfully.',
        content: {
          'application/json': {
            schema: {
              type: 'object',
              properties: {
                ok: {
                  const: true,
                  description: 'Whether the operation succeeded.',
                },
              },
              required: ['ok'],
            },
          },
        },
      },
      '401': {
        description: 'Unauthorized.',
        content: {
          'application/json': {
            example: {
              error: {
                message: 'Unauthorized.',
                code: 'unauthorized',
                status: 401,
              },
            },
            schema: {
              $ref: '#/components/schemas/ApiError',
            },
          },
        },
      },
      '404': {
        description: 'Not found.',
        content: {
          'application/json': {
            example: {
              error: {
                message: 'Not found.',
                code: 'not-found',
                status: 404,
              },
            },
            schema: {
              $ref: '#/components/schemas/ApiError',
            },
          },
        },
      },
    },
  } as ZodOpenApiOperationObject,
});

const operation2 = defineOperation({
  method: 'get',
  path: '/api/websites/{websiteId}/segments/{segmentId}',
  audience: 'public',
  auth: 'bearer-or-share',
  operation: {
    operationId: 'getWebsiteSegment',
    summary: 'Get websites website id segments segment id',
    description: 'Returns a saved segment or cohort and its filter parameters for the website.',
    tags: ['Websites'],
    parameters: [
      {
        name: 'websiteId',
        in: 'path',
        required: true,
        schema: {
          type: 'string',
        },
        description: 'ID of the website.',
      },
      {
        name: 'segmentId',
        in: 'path',
        required: true,
        schema: {
          type: 'string',
        },
        description: 'ID of the saved segment or cohort.',
      },
    ],
    responses: {
      '200': {
        description: 'The operation completed successfully.',
        content: {
          'application/json': {
            schema: {
              type: 'object',
              properties: {
                id: {
                  type: 'string',
                  description: 'Unique identifier of the resource.',
                },
                createdAt: {
                  type: 'string',
                  format: 'date-time',
                  description: 'Date and time the record was created.',
                },
                updatedAt: {
                  type: 'string',
                  format: 'date-time',
                  description: 'Date and time the record was last updated.',
                },
                name: {
                  type: 'string',
                  description: 'Display name of the resource.',
                },
                type: {
                  type: 'string',
                },
                parameters: {
                  anyOf: [
                    {
                      type: 'string',
                    },
                    {
                      type: 'number',
                    },
                    {
                      const: false,
                    },
                    {
                      const: true,
                    },
                    {
                      type: 'object',
                      properties: {},
                      additionalProperties: {
                        anyOf: [
                          {
                            type: 'string',
                          },
                          {
                            type: 'number',
                          },
                          {
                            const: false,
                          },
                          {
                            const: true,
                          },
                          {},
                          {
                            type: 'object',
                            properties: {
                              length: {
                                type: 'number',
                              },
                            },
                            required: ['length'],
                          },
                        ],
                      },
                    },
                    {
                      type: 'object',
                      properties: {
                        length: {
                          type: 'number',
                        },
                      },
                      required: ['length'],
                    },
                  ],
                  description: 'Configuration parameters for the resource.',
                },
                websiteId: {
                  type: 'string',
                  description: 'ID of the website.',
                },
              },
              required: ['id', 'createdAt', 'updatedAt', 'name', 'type', 'parameters', 'websiteId'],
            },
          },
        },
      },
      '401': {
        description: 'Unauthorized.',
        content: {
          'application/json': {
            example: {
              error: {
                message: 'Unauthorized.',
                code: 'unauthorized',
                status: 401,
              },
            },
            schema: {
              $ref: '#/components/schemas/ApiError',
            },
          },
        },
      },
      '404': {
        description: 'Not found.',
        content: {
          'application/json': {
            example: {
              error: {
                message: 'Not found.',
                code: 'not-found',
                status: 404,
              },
            },
            schema: {
              $ref: '#/components/schemas/ApiError',
            },
          },
        },
      },
    },
  } as ZodOpenApiOperationObject,
});

const operation3 = defineOperation({
  method: 'post',
  path: '/api/websites/{websiteId}/segments/{segmentId}',
  audience: 'public',
  auth: 'bearer',
  operation: {
    operationId: 'updateWebsiteSegment',
    summary: 'Create or update websites website id segments segment id',
    description: "Updates a saved segment or cohort's type, name, and filter parameters.",
    tags: ['Websites'],
    parameters: [
      {
        name: 'websiteId',
        in: 'path',
        required: true,
        schema: {
          type: 'string',
        },
        description: 'ID of the website.',
      },
      {
        name: 'segmentId',
        in: 'path',
        required: true,
        schema: {
          type: 'string',
        },
        description: 'ID of the saved segment or cohort.',
      },
    ],
    requestBody: {
      required: true,
      content: {
        'application/json': {
          schema: {
            type: 'object',
            properties: {
              type: {
                type: 'string',
                enum: ['segment', 'cohort'],
              },
              name: {
                type: 'string',
                maxLength: 200,
                description: 'Display name of the resource.',
              },
              parameters: {
                type: 'object',
                properties: {
                  filters: {
                    type: 'array',
                    items: {
                      type: 'object',
                      additionalProperties: true,
                    },
                    description: 'Filters applied to the analytics data.',
                  },
                  match: {
                    type: 'string',
                    enum: ['all', 'any'],
                    description: 'Whether records must match all filters or any filter.',
                  },
                  dateRange: {
                    type: 'string',
                  },
                  action: {
                    type: 'object',
                    properties: {
                      type: {
                        type: 'string',
                      },
                      value: {
                        type: 'string',
                      },
                    },
                    required: ['type', 'value'],
                  },
                },
                description: 'Configuration parameters for the resource.',
              },
            },
            required: ['type', 'name', 'parameters'],
          },
        },
      },
    },
    responses: {
      '200': {
        description: 'The operation completed successfully.',
        content: {
          'application/json': {
            schema: {
              type: 'object',
              properties: {
                id: {
                  type: 'string',
                  description: 'Unique identifier of the resource.',
                },
                createdAt: {
                  type: 'string',
                  format: 'date-time',
                  description: 'Date and time the record was created.',
                },
                updatedAt: {
                  type: 'string',
                  format: 'date-time',
                  description: 'Date and time the record was last updated.',
                },
                name: {
                  type: 'string',
                  description: 'Display name of the resource.',
                },
                type: {
                  type: 'string',
                },
                parameters: {
                  anyOf: [
                    {
                      type: 'string',
                    },
                    {
                      type: 'number',
                    },
                    {
                      const: false,
                    },
                    {
                      const: true,
                    },
                    {
                      type: 'object',
                      properties: {},
                      additionalProperties: {
                        anyOf: [
                          {
                            type: 'string',
                          },
                          {
                            type: 'number',
                          },
                          {
                            const: false,
                          },
                          {
                            const: true,
                          },
                          {},
                          {
                            type: 'object',
                            properties: {
                              length: {
                                type: 'number',
                              },
                            },
                            required: ['length'],
                          },
                        ],
                      },
                    },
                    {
                      type: 'object',
                      properties: {
                        length: {
                          type: 'number',
                        },
                      },
                      required: ['length'],
                    },
                  ],
                  description: 'Configuration parameters for the resource.',
                },
                websiteId: {
                  type: 'string',
                  description: 'ID of the website.',
                },
              },
              required: ['id', 'createdAt', 'updatedAt', 'name', 'type', 'parameters', 'websiteId'],
            },
          },
        },
      },
      '400': {
        description: 'Bad request.',
        content: {
          'application/json': {
            example: {
              error: {
                message: 'Bad request.',
                code: 'bad-request',
                status: 400,
              },
            },
            schema: {
              $ref: '#/components/schemas/ApiError',
            },
          },
        },
      },
      '401': {
        description: 'Unauthorized.',
        content: {
          'application/json': {
            example: {
              error: {
                message: 'Unauthorized.',
                code: 'unauthorized',
                status: 401,
              },
            },
            schema: {
              $ref: '#/components/schemas/ApiError',
            },
          },
        },
      },
      '404': {
        description: 'Not found.',
        content: {
          'application/json': {
            example: {
              error: {
                message: 'Not found.',
                code: 'not-found',
                status: 404,
              },
            },
            schema: {
              $ref: '#/components/schemas/ApiError',
            },
          },
        },
      },
    },
  } as ZodOpenApiOperationObject,
});

export const operations = [operation1, operation2, operation3] as const;
