// Generated by `pnpm openapi:contracts`. Do not edit directly.

import type { ZodOpenApiOperationObject } from 'zod-openapi';
import { defineOperation } from '@/openapi/operation';

const operation1 = defineOperation({
  method: 'get',
  path: '/api/me',
  audience: 'public',
  auth: 'bearer',
  operation: {
    operationId: 'getMe',
    summary: 'Get me',
    tags: ['Account'],
    'x-umami-oauth-scope': 'websites:read',
    responses: {
      '200': {
        description: 'The operation completed successfully.',
        content: {
          'application/json': {
            schema: {
              type: 'object',
              properties: {
                user: {
                  type: 'object',
                  properties: {
                    id: {
                      type: 'string',
                    },
                    username: {
                      type: 'string',
                    },
                    role: {
                      type: 'string',
                    },
                    isAdmin: {
                      type: 'boolean',
                    },
                  },
                  required: ['id', 'username', 'role', 'isAdmin'],
                },
                apiKey: {
                  type: 'object',
                  properties: {
                    id: {
                      type: 'string',
                    },
                    name: {
                      type: 'string',
                    },
                  },
                  required: ['id', 'name'],
                },
                authType: {
                  anyOf: [
                    {
                      const: 'session',
                    },
                    {
                      const: 'share',
                    },
                    {
                      const: 'api-key',
                    },
                    {
                      const: 'oauth',
                    },
                  ],
                },
                oauth: {
                  type: 'object',
                  properties: {
                    clientId: {
                      type: 'string',
                    },
                    scopes: {
                      type: 'array',
                      items: {
                        type: 'string',
                      },
                    },
                    tokenId: {
                      type: 'string',
                    },
                  },
                  required: ['clientId', 'scopes'],
                },
                shareToken: {
                  type: 'object',
                  properties: {
                    shareType: {
                      type: 'number',
                    },
                    websiteId: {
                      type: 'string',
                    },
                    websiteIds: {
                      type: 'array',
                      items: {
                        type: 'string',
                      },
                    },
                    boardId: {
                      type: 'string',
                    },
                    pixelId: {
                      type: 'string',
                    },
                    pixelIds: {
                      type: 'array',
                      items: {
                        type: 'string',
                      },
                    },
                    linkId: {
                      type: 'string',
                    },
                    linkIds: {
                      type: 'array',
                      items: {
                        type: 'string',
                      },
                    },
                    parameters: {
                      type: 'object',
                      properties: {
                        allowFilter: {
                          type: 'boolean',
                        },
                        theme: {
                          anyOf: [
                            {
                              const: 'light',
                            },
                            {
                              const: 'dark',
                            },
                          ],
                        },
                      },
                      additionalProperties: {
                        anyOf: [
                          {
                            const: false,
                          },
                          {
                            const: true,
                          },
                          {
                            const: 'light',
                          },
                          {
                            const: 'dark',
                          },
                        ],
                      },
                    },
                  },
                },
              },
            },
          },
        },
      },
      '401': {
        description: 'Unauthorized.',
        content: {
          'application/json': {
            example: {
              error: {
                message: 'Unauthorized.',
                code: 'unauthorized',
                status: 401,
              },
            },
            schema: {
              $ref: '#/components/schemas/ApiError',
            },
          },
        },
      },
    },
  } as ZodOpenApiOperationObject,
});

export const operations = [operation1] as const;
