// Generated by `pnpm openapi:contracts`. Do not edit directly.

import type { ZodOpenApiOperationObject } from 'zod-openapi';
import { defineOperation } from '@/openapi/operation';

const operation1 = defineOperation({
  method: 'post',
  path: '/api/reports/journey',
  audience: 'public',
  auth: 'bearer-or-share',
  operation: {
    operationId: 'postReportsJourney',
    summary: 'Create or update reports journey',
    description:
      'Create or update reports journey. The request and response models are derived from the validated route contract.',
    tags: ['Reports'],
    requestBody: {
      required: true,
      content: {
        'application/json': {
          schema: {
            type: 'object',
            properties: {
              websiteId: {
                type: 'string',
                format: 'uuid',
              },
              filters: {
                type: 'object',
                additionalProperties: true,
              },
              type: {
                type: 'string',
              },
              parameters: {
                type: 'object',
                additionalProperties: true,
              },
            },
            required: ['websiteId', 'filters', 'type', 'parameters'],
          },
        },
      },
    },
    responses: {
      '200': {
        description: 'The operation completed successfully.',
        content: {
          'application/json': {
            schema: {
              type: 'array',
              items: {
                type: 'object',
                properties: {
                  e1: {
                    type: 'string',
                  },
                  e2: {
                    type: 'string',
                  },
                  e3: {
                    type: 'string',
                  },
                  e4: {
                    type: 'string',
                  },
                  e5: {
                    type: 'string',
                  },
                  e6: {
                    type: 'string',
                  },
                  e7: {
                    type: 'string',
                  },
                  count: {
                    type: 'number',
                  },
                },
                required: ['e1', 'e2', 'e3', 'e4', 'e5', 'e6', 'e7', 'count'],
              },
            },
          },
        },
      },
      '400': {
        description: 'Bad request.',
        content: {
          'application/json': {
            example: {
              error: {
                message: 'Bad request.',
                code: 'bad-request',
                status: 400,
              },
            },
            schema: {
              $ref: '#/components/schemas/ApiError',
            },
          },
        },
      },
      '401': {
        description: 'Unauthorized.',
        content: {
          'application/json': {
            example: {
              error: {
                message: 'Unauthorized.',
                code: 'unauthorized',
                status: 401,
              },
            },
            schema: {
              $ref: '#/components/schemas/ApiError',
            },
          },
        },
      },
    },
  } as ZodOpenApiOperationObject,
});

export const operations = [operation1] as const;
