// Generated by `pnpm openapi:contracts`. Do not edit directly.

import type { ZodOpenApiOperationObject } from 'zod-openapi';
import { defineOperation } from '@/openapi/operation';

const operation1 = defineOperation({
  method: 'get',
  path: '/api/teams/{teamId}/users',
  audience: 'public',
  auth: 'bearer-or-share',
  operation: {
    operationId: 'getTeamsTeamIdUsers',
    summary: 'Get teams team id users',
    description:
      'Get teams team id users. The request and response models are derived from the validated route contract.',
    tags: ['Teams'],
    parameters: [
      {
        name: 'teamId',
        in: 'path',
        required: true,
        schema: {
          type: 'string',
        },
      },
      {
        name: 'page',
        in: 'query',
        required: false,
        schema: {
          type: 'integer',
          minimum: 1,
        },
      },
      {
        name: 'pageSize',
        in: 'query',
        required: false,
        schema: {
          type: 'integer',
          minimum: 1,
        },
      },
      {
        name: 'maxResults',
        in: 'query',
        required: false,
        schema: {
          type: 'integer',
          minimum: 1,
        },
      },
      {
        name: 'search',
        in: 'query',
        required: false,
        schema: {
          type: 'string',
        },
      },
    ],
    responses: {
      '200': {
        description: 'The operation completed successfully.',
        content: {
          'application/json': {
            schema: {
              type: 'object',
              properties: {
                data: {
                  type: 'array',
                  items: {
                    allOf: [
                      {
                        type: 'object',
                        properties: {
                          id: {
                            type: 'string',
                          },
                          userId: {
                            type: 'string',
                          },
                          createdAt: {
                            type: 'string',
                            format: 'date-time',
                          },
                          updatedAt: {
                            type: 'string',
                            format: 'date-time',
                          },
                          role: {
                            type: 'string',
                          },
                          teamId: {
                            type: 'string',
                          },
                        },
                        required: ['id', 'userId', 'createdAt', 'updatedAt', 'role', 'teamId'],
                      },
                      {
                        type: 'object',
                        properties: {
                          user: {
                            type: 'object',
                            properties: {
                              id: {
                                type: 'string',
                              },
                              username: {
                                type: 'string',
                              },
                            },
                            required: ['id', 'username'],
                          },
                        },
                      },
                    ],
                  },
                },
                count: {
                  type: 'number',
                },
                page: {
                  type: 'number',
                },
                pageSize: {
                  type: 'number',
                },
                orderBy: {
                  type: 'string',
                },
                sortDescending: {
                  type: 'boolean',
                },
                search: {
                  type: 'string',
                },
                isCapped: {
                  type: 'boolean',
                },
              },
              required: ['data', 'count', 'page', 'pageSize'],
            },
          },
        },
      },
      '400': {
        description: 'Bad request.',
        content: {
          'application/json': {
            example: {
              error: {
                message: 'Bad request.',
                code: 'bad-request',
                status: 400,
              },
            },
            schema: {
              $ref: '#/components/schemas/ApiError',
            },
          },
        },
      },
      '401': {
        description: 'Unauthorized.',
        content: {
          'application/json': {
            example: {
              error: {
                message: 'Unauthorized.',
                code: 'unauthorized',
                status: 401,
              },
            },
            schema: {
              $ref: '#/components/schemas/ApiError',
            },
          },
        },
      },
    },
  } as ZodOpenApiOperationObject,
});

const operation2 = defineOperation({
  method: 'post',
  path: '/api/teams/{teamId}/users',
  audience: 'public',
  auth: 'bearer',
  operation: {
    operationId: 'postTeamsTeamIdUsers',
    summary: 'Create or update teams team id users',
    description:
      'Create or update teams team id users. The request and response models are derived from the validated route contract.',
    tags: ['Teams'],
    parameters: [
      {
        name: 'teamId',
        in: 'path',
        required: true,
        schema: {
          type: 'string',
        },
      },
    ],
    requestBody: {
      required: true,
      content: {
        'application/json': {
          schema: {
            type: 'object',
            properties: {
              userId: {
                type: 'string',
                format: 'uuid',
              },
              role: {
                type: 'string',
                enum: ['team-member', 'team-view-only', 'team-manager'],
              },
            },
            required: ['userId', 'role'],
          },
        },
      },
    },
    responses: {
      '200': {
        description: 'The operation completed successfully.',
        content: {
          'application/json': {
            schema: {
              type: 'object',
              properties: {
                id: {
                  type: 'string',
                },
                userId: {
                  type: 'string',
                },
                createdAt: {
                  type: 'string',
                  format: 'date-time',
                },
                updatedAt: {
                  type: 'string',
                  format: 'date-time',
                },
                role: {
                  type: 'string',
                },
                teamId: {
                  type: 'string',
                },
              },
              required: ['id', 'userId', 'createdAt', 'updatedAt', 'role', 'teamId'],
            },
          },
        },
      },
      '400': {
        description: 'Bad request.',
        content: {
          'application/json': {
            example: {
              error: {
                message: 'Bad request.',
                code: 'bad-request',
                status: 400,
              },
            },
            schema: {
              $ref: '#/components/schemas/ApiError',
            },
          },
        },
      },
      '401': {
        description: 'Unauthorized.',
        content: {
          'application/json': {
            example: {
              error: {
                message: 'Unauthorized.',
                code: 'unauthorized',
                status: 401,
              },
            },
            schema: {
              $ref: '#/components/schemas/ApiError',
            },
          },
        },
      },
    },
  } as ZodOpenApiOperationObject,
});

export const operations = [operation1, operation2] as const;
