// Generated by `pnpm openapi:contracts`. Do not edit directly.

import type { ZodOpenApiOperationObject } from 'zod-openapi';
import { defineOperation } from '@/openapi/operation';

const operation1 = defineOperation({
  method: 'delete',
  path: '/api/pixels/{pixelId}',
  audience: 'public',
  auth: 'bearer',
  operation: {
    operationId: 'deletePixelsPixelId',
    summary: 'Delete pixels pixel id',
    tags: ['Pixels'],
    parameters: [
      {
        name: 'pixelId',
        in: 'path',
        required: true,
        schema: {
          type: 'string',
        },
      },
    ],
    responses: {
      '200': {
        description: 'The operation completed successfully.',
        content: {
          'application/json': {
            schema: {
              type: 'object',
              properties: {
                ok: {
                  const: true,
                },
              },
              required: ['ok'],
            },
          },
        },
      },
      '401': {
        description: 'Unauthorized.',
        content: {
          'application/json': {
            example: {
              error: {
                message: 'Unauthorized.',
                code: 'unauthorized',
                status: 401,
              },
            },
            schema: {
              $ref: '#/components/schemas/ApiError',
            },
          },
        },
      },
    },
  } as ZodOpenApiOperationObject,
});

const operation2 = defineOperation({
  method: 'get',
  path: '/api/pixels/{pixelId}',
  audience: 'public',
  auth: 'bearer-or-share',
  operation: {
    operationId: 'getPixelsPixelId',
    summary: 'Get pixels pixel id',
    tags: ['Pixels'],
    parameters: [
      {
        name: 'pixelId',
        in: 'path',
        required: true,
        schema: {
          type: 'string',
        },
      },
    ],
    responses: {
      '200': {
        description: 'The operation completed successfully.',
        content: {
          'application/json': {
            schema: {
              type: 'object',
              properties: {
                id: {
                  type: 'string',
                },
                userId: {
                  type: 'string',
                },
                createdAt: {
                  type: 'string',
                  format: 'date-time',
                },
                updatedAt: {
                  type: 'string',
                  format: 'date-time',
                },
                deletedAt: {
                  type: 'string',
                  format: 'date-time',
                },
                name: {
                  type: 'string',
                },
                teamId: {
                  type: 'string',
                },
                slug: {
                  type: 'string',
                },
              },
              required: [
                'id',
                'userId',
                'createdAt',
                'updatedAt',
                'deletedAt',
                'name',
                'teamId',
                'slug',
              ],
            },
          },
        },
      },
      '401': {
        description: 'Unauthorized.',
        content: {
          'application/json': {
            example: {
              error: {
                message: 'Unauthorized.',
                code: 'unauthorized',
                status: 401,
              },
            },
            schema: {
              $ref: '#/components/schemas/ApiError',
            },
          },
        },
      },
    },
  } as ZodOpenApiOperationObject,
});

const operation3 = defineOperation({
  method: 'post',
  path: '/api/pixels/{pixelId}',
  audience: 'public',
  auth: 'bearer',
  operation: {
    operationId: 'postPixelsPixelId',
    summary: 'Create or update pixels pixel id',
    tags: ['Pixels'],
    parameters: [
      {
        name: 'pixelId',
        in: 'path',
        required: true,
        schema: {
          type: 'string',
        },
      },
    ],
    requestBody: {
      required: true,
      content: {
        'application/json': {
          schema: {
            type: 'object',
            properties: {
              name: {
                type: 'string',
                maxLength: 100,
              },
              slug: {
                type: 'string',
                minLength: 8,
                maxLength: 100,
              },
            },
          },
        },
      },
    },
    responses: {
      '200': {
        description: 'The operation completed successfully.',
        content: {
          'application/json': {
            schema: {
              type: 'object',
              properties: {
                id: {
                  type: 'string',
                },
                userId: {
                  type: 'string',
                },
                createdAt: {
                  type: 'string',
                  format: 'date-time',
                },
                updatedAt: {
                  type: 'string',
                  format: 'date-time',
                },
                deletedAt: {
                  type: 'string',
                  format: 'date-time',
                },
                name: {
                  type: 'string',
                },
                teamId: {
                  type: 'string',
                },
                slug: {
                  type: 'string',
                },
              },
              required: [
                'id',
                'userId',
                'createdAt',
                'updatedAt',
                'deletedAt',
                'name',
                'teamId',
                'slug',
              ],
            },
          },
        },
      },
      '400': {
        description: 'Bad request.',
        content: {
          'application/json': {
            example: {
              error: {
                message: 'Bad request.',
                code: 'bad-request',
                status: 400,
              },
            },
            schema: {
              $ref: '#/components/schemas/ApiError',
            },
          },
        },
      },
      '401': {
        description: 'Unauthorized.',
        content: {
          'application/json': {
            example: {
              error: {
                message: 'Unauthorized.',
                code: 'unauthorized',
                status: 401,
              },
            },
            schema: {
              $ref: '#/components/schemas/ApiError',
            },
          },
        },
      },
      '500': {
        description: 'Server error.',
        content: {
          'application/json': {
            example: {
              error: {
                message: 'Server error.',
                code: 'server-error',
                status: 500,
              },
            },
            schema: {
              $ref: '#/components/schemas/ApiError',
            },
          },
        },
      },
    },
  } as ZodOpenApiOperationObject,
});

export const operations = [operation1, operation2, operation3] as const;
